+++
title = "Immortal Frontier"
subtitle = "Introduction"
date = 2020-04-11T14:03:02-05:00
draft = true
categories = [
  "Zines",
]
title-font = "https://fonts.google.com/specimen/Poiret+One?category=Sans+Serif,Display,Monospace&preview.text=IMMORT%D0%9BL+FRONTIER&preview.text_type=custom&preview.size=120&preview.layout=row&sidebar.open&selection.family=Poiret+One&query=poi"
+++

Immortal Frontier is a space opera tabletop role-playing game about
badass spaceships, capatalism, imperialism, and revolution.

* Another possible setting

  Humanity has spread to Mars and the belt. The belters (find a
  different name), knowing that Jupiter kept the rocks in the belt
  from combining and forming into the plannet they would have, see
  their desitny as combining the rocks into their own plannet.

  Martians are oppulant as fuck because Mars is the subburb that the
  rich fled to and earth was the urban sprawl left behind. Punks
  anarchists and workers ended up at the belt

* Breif
** Big idea

   Alistar Reynolds, Peter F. Hamilton, and EVE Online
   * Spaceships
   * Huge far future sandbox
   * Immortality
   * Strategic and tactical combat
   * Social organization (corperations, enterprises, pirate gangs,
     sovereignty, alliances, etc.)
   * Politics
   * Industry
   * Economics

** Ideal play experience

   * Loadout theorycrafting for
   * Tactical space combat in order to
   * Defend and advance your industrial and economic enterprise to
   * Achieve grand self determined aspirations in a
   * Vast, hostile, and dangerious universe

** Broad concepts

   * Sandbox
   * Space Combat
   * Politics
   * Industry
   * Economics
   * Factions

** Constraints

   * Playable at the table with dice, cards, rulebooks, pen, and
     paper
   * Get a mix of play in a 2-4 hour session. Some combat, industry,
     politics, social RP etc.
   * 3+ players
   * Small core game, very expandable, metadata driven

* Dice

  The rules will often call for rolling some dice to see how
  something turns out. Always roll d6s. Roll them in pools with a
  number of dice determined by a stat. A pool might be 1d6 or 20d6
  depending on the situation. Either get lots of dice of a few
  different colors (I reccomend 12mm dice so you can hold a lot of
  them) or use an online dice roller.

  Every roll references a table---or tables---listing up to 6
  possible outcomes. When you roll, you'll assign up to your---or
  your ships---rank in dice to those outcomes.

  For example. Say you are in a rank 2 ship, and you are trying to
  get a target lock on an enemy ship. Your ship description lists its
  built in targeting table as follows

  | roll | effect         |
  |------+----------------|
  |    1 | lose all locks |
  |    2 | lose 2 locks   |
  |    3 | none           |
  |    4 | none           |
  |    5 | gain 1 lock    |
  |    6 | gain 2 locks   |

  You have the targeting computer skill at rank 3 which lists a
  targeting table as follows.

  | roll | effect       |
  |------+--------------|
  |    1 | lose 2 locks |
  |    2 | none         |

  Following the rules for Combat below, you determine that your pool
  for this roll is 3 dice. Your roll comes up [1, 1, 5]. Since your
  rank is 2, you chose two of the rolls effects to occur (in any
  order). You choose a 1 and the 5. First you assign the 1 to the 1
  effect from the targeting computer skill and "lose 2 locks" then
  assign the 5 to the ships built in targeting computer table and
  gain 1 lock.

  Next round you roll for locks and get [1, 2, 6]. You chose the 2
  and the 6 to assign, assigning the two to the targeting computer
  skill table (none) and the 6 to the ship targeting computer table
  and gain targeting locks on 2 ships.

* Experience and Skills

  Skill Points may be bought, at any time, if a Character has enough
  Experience points to pay for them. Each rank in a skill costs the
  skills Level plus the Rank you are buying. For example: you have 3
  ranks in Battlecruiser and want to buy the fourth.  Battlecruiser is
  a level two skill and you want to buy the fourth rank. So that costs
  6 Experience Points. The Level (2) plus the Rank (4)

  Experience points are earned in real player time, and you can adjust
  how quickly that happens based on how fast you want your advancement
  to go. By default earn 2 experience points a week. There are no
  skills that make earning experience points faster.

** Frigate Combat Operations

   Rank: 0

** Laser Combat Operations

   Rank: 0

** Missile Combat Operations

   Rank: 0

** Flak Cannon Combat Operations

   Rank: 0

** Warp Jamming

   Rank: 0

** Overheating

   Rank: 0

** Shield Defense

   Rank: 0

** Armor Defense

   Rank: 0

** Targeting Computer

   Rank 3

   When using a targeting computer to gain locks on ships in
   space---including the computer built into the ship---these effects
   are available.

   | roll | effect      |
   |------+-------------|
   |    1 | lose 1 lock |
   |    2 | none        |

* Cash and Gear

  Cash is an abstracted stat that each character has, though they
  start with zero. It represents that character's purchasing power and
  is a pool of dice that's rolled to see what you can afford at a
  given time, if it's even available. Gear availability is also an
  abstracted dice pool. Each item is either Common (always available)
  or it has a Rarity stat. It's either Cheap (always affordable) or it
  has an Price stat. Whenever you want to buy something roll your
  Cash, the item's Rarity, and its Price. If your Cash hits *times*
  the Rarity hits is greater than the Price hits, then its available
  and affordable. If there are any Rarity hits then it's available and
  you can permenantly reduce your Cash stat by one to increase your
  number of Cash hits by one. You'll have the opportunity to increase
  your Cash stat through the course of playing scenes

** Peice of Shit Frigate

   Price: Cheap
   Rarity: Common
   Size: 7
   Defense Hardpoints: 1
   Weapon Hardpoints: 2
   Prerequisites: Frigate Combat Operations 1

   Shitty small Frigate. It'll get you station to station, and carry a
   gun, but it's pretty bad and you'll want to replace it as soon as
   you can. Aparently that's why they are always available

** Small Laser

   Price: Cheap
   Rarity: Common
   Range: 2
   Damage: 2
   Prerequisites: Laser Combat Operations 1

   put them on your spaceship and they pew pew, what more do you want?

   Damage reduced with Shields

** Small Missile Battery

   Price: Cheap
   Rarity: Common
   Range: 3
   Tracking: 2
   Damage: 1
   Prerequisites: Missile Combat Operations 1

   A battery of 6 missiles that autotrack a locked target and blow up on impact

   For Attack rolls treat their Speed pool as Radial Velocity

   Attacker chooses either Armor or Shield durring the attack. Damage
   reduced with that.

** Small Flak Cannon

   Price: Cheap
   Rarity: Common
   Range: 1
   Tracking: 3
   Damage: 2
   Prerequisites: Flak Cannon Combat Operations 1

   Close range simple and reliable brawling weaponry. Cannons fire
   proximity mortars that explode near targets spraying shrapnel
   towards them

   Damage reduced with Armor

** Warp Jammer

   Price: Cheap
   Rarity: Common
   Range: 2
   Prerequisites: Warp Jamming 1

** Small Shield Generator

   Shield: 2
   Prerequisites: Shield Defense 1

   Generates a force field that dicipates electromagnetic and theamal
   attacks efficiently

** Small Armor Plates

   Armor: 2
   Prerequisites: Armor Defense 1

   Thick plates of graphine epoxy-fullerene laminate and concrete
   bolted to the exterrior of the ship. Heavy and reliable

* Space Combat
** Engage

   When enemy ships are in your local area you may *engage* them, or
   they may *engage* you. Both sides of the engagement follow the
   procedure simultaneously with each each step informing the
   following steps.

   When you start an engagement or new ships join, establish the
   range between you and the other ships. Every player rolls a number
   of d6s equal to their engines pool. the SC does the same for every
   enemy ship. Whatever side did not initiate the engagement assigns
   a die from their roll to each ship that they can. The other side
   may then assign dice from their pool to either add to or subtract
   from the opposing assignment to a max of 6 and a minimum of 1. If
   there are not enough dice to assign to all the ships the initiator
   may choose starting ranges for ships that did not assign dice to
   them.

   An engagement occurs in rounds with 4 phases each. Everyone
   executes each phase in order simultaniously. When order matters
   for effects, the piolot of the affected ship chooses the order of
   effects.

   *Sensors*
   * Describe the engagement
   * Say what is obvious
   * Roll Sensors

   *Engineering*
   * Assign Engineeting dice to Speed, Maneuverability, Repair, and Warp
     pools then roll them

   *Designers Note* Speed tables let you manipulate range,
   Maneuverability tables let you effect opponents Damage or Sensors
   tables for a round and Repair tables let you repair the ship. The
   Warp table works in steps. The "Prepare for warp" effect adds
   "Warp off" options to the Warp tables so it takes a round to
   prepare then you can try to warp off. Warp jammers

   *Attack*
   * Assign Gunnery dice to Damage and Accuracy pools then roll.

   *Designers Note* Damage tables do more damage but are susceptible
   to manuvering. Accuracy tables are not susceptible to anything but
   the most extreme maneuvering. Missiles have identical damage and
   accuracy tables, but may be outrun.

   *Defenses*
   * Note what damage types each hit causes and roll Defenses. For
     each assignment chose the column matching the damage type you
     want to effect.

   *Designers Note* Defenses come with 3 tables, one for Shields, one
   for Armor, and one for Hull. Shields effects will tend to effect
   future shield rolls in the same way that maneuverability can
   affect Damage and Sensors. Armor tracks an amount of armor that
   works like hit points, and hull damage starts to reduce your dice
   pools.

* /Industry/
* /Enterprise/
* /Politics/
* /Sovereignty/


