+++
title = "Life Vigilante"
subtitle = "What will you risk to fight for justice"
date = 2020-04-21T08:11:12-05:00
draft = true
categories = [
  "Micro Games",
]
+++

The object of the game is to become attached to the life you've built
then complicate or lose it to fight injustice. The object of the game
is to get a lot to lose, and lose it to uphold your convictions.

Play to find out what they accomplish in their lives, what change they
make to society, and what they give up to do it.

* Set up
** Protagonist

   All players except the Game Master (GM) create a protagonist
   character that they'll play and be responsible for through their
   whole story. To create a protagonist, follow the Life and Vigilante
   sections below.

*** Life

    Write about your real life. Choose a /Real Name/. Write a few
    /life goals/. Make them things you really care about. Things that
    would be tragic to give up. For example: "Start a family" or
    "Build a rewarding career". Write two starting *acomplishments*
    and keep track of your *frustration* level starting at 1.

*** Vigilante

    Write about your secret identity. Choose an /alias/ and describe
    your /costume/. Write a few /convictions/. Make them things you
    really care about. Things you would be willing to risk your life
    to defend and uphold. Write one vigilante deed you did to uphold
    your /convicions/, write this along with your other
    *acomplishments*. Don't make it too risky. Keep track of your
    *Risk* level starting at 1

** Systems of Injustice

   The GM plays everything other than the protagonists. They'll set the
   scene, and challenge the protagonists. They'll respond as the city
   and its systems of injustice manuvering to maintain their power and
   privilege.

   The GM, collaborating with the rest of the group, creates the
   setting. They write about the city and its systems of injustice.
   Discuss this with the group and make sure everyone is cool with the
   city and especially the systems of injustice y'all are going to be
   exploring.  If someone's not into it /for any reason/ it's not going
   to make for a very good game. /Life Vigilante/ gets one thousand
   times better when everyone is on the same page about the systems of
   injustice you'll be exploring and fighting against.

   Write some details about the city. Name the /city/ the /mayor/ and
   the /cheif of police/. Name an /investigative reporter/, a /tabloid
   reporter/ and a /pop culture influencer/. Use these as foci for
   envisioning the city and its systems of injustice. Feel free to
   write more details as you find use for more throughout play. Drown
   everything in pulp, grit, and camp.

   Write two /mainstream values/ that maintain the systems of
   injustice.

   Discuss the /mainstream values/ with the group. How do they turn
   people to villainy? What villainous behaviors do they allow to
   flourish? How do they turn people villainous? How villianous people
   take advantage? Note down some of these ideas with the rest of the
   city details for the group to refer back to and for the GM to use
   as inspiration when establishing villains and their machinations
   when the truth of the narrative demands.

* The Rules

  Play by the rules long enough to get good at running them so you see
  how they run when everyone knows how. Then if you see something you
  want to change, change it. Just give these rules the old college try
  first.

  Play occurs in one of three modes. *Real Messy Life*, *Vigilante
  Action* or *Mainstream Takes*. Start wherever you have a vision of and
  follow the rules for the mode. They will tell you how to play it and
  how to transition to the others.

** The Dice

   The various rules will sometimes tell you to /roll *advantages*
   against some stat or another./ That means to assemble two pools
   (handfulls) of dice---use different color six sided dice for each
   pool. One is for the stat you are rolling against, it's the
   *opposing pool* and is a number of dice equal to the stat that the
   rule called for. The other is yours and it's one die for each
   *accomplishment* you are using to your *advantage* in the
   situation. Only use *accomplishments* you can reasonably justify as
   advantagous and are willing to risk *comlicating* (discussed
   below). Roll them both. If *your pool* rolls more fives and sixes
   (5+) than the *opposing pool* rolled you got a *hit*, if it has
   more than twice as many, you got a *strong hit*. Otherwise you
   *missed*.

   *Acomplishments* can only be used for advantage if they don't have
   a *complication*

*** Acomplishments

    Sometimes throughout play you'll make and write down
    *acomplishments*. These can be used in rolls when they are an
    *advantage* in the situation. All protagonists wrote some during
    character creation.

    For example, *acomplishments* could be:
    * Built a stable partnerhsip with Alex
    * Took a job as a lawyer at Noether and Nash
    * Got a 30 year mortgage on a three bedroom in Parkwood Heights

    *Acomplishments* can be repeated or expanded, keep track of how
    many times this has happened. Each counts as its own
    *acomplishment* so each can have a *complication*, and each can be
    used for for dice when they are *advantagious* given the
    situation. For example you could mark multiple *acomplishments* on
    the mortgage to represent paying it down or mark multiple
    *acomplishments* on the job to represent promotions. Choose
    whatever makes sense to the fiction.

*** Complications

    *Complications* get in the way of using acomplishments to your
    *advantage*. You may not use a *complicated* *accomplishment* as
    *advantage* in any rolls. When an *accomplishment* gets
    *complicated* write the *complication* next to the *acomplishment*.

    For example:
    * A mortgage is complicated by a lien or a cracked foundation.
    * A job is complicated by poor performance reviews

** Real Messy Life

   When a character intends to *acomplish* something meaningful or
   intends to resolve a *complication* that's *real messy life*.
   You'll frame the scene, roll to see where it needs to end up then
   play it out. You can make this roll sometime within the scene at
   its critical moment if you prefer

   This may be something like making friends, deepening a persional
   connection etc. It could be building or buying something, learning
   something, practicing something, or progressing your career

   1. State your intent. What you want the outcome to be? Specify what
      you want to *acomplish* or the *complication* you want to
      resolve
   2. Describe how you are going to do it. Say what *acomplishments*
      you are using to your *advantage*, and how they are
      advantagous. This frames the scene you'll play out after you...
   3. Roll against *frustration*

   *Strong Hit*
   * Play out the scene and write an *acomplishment* or resolve the
     *complication*

   *Hit*
   * Play out the scene and write an *acomplishment* or resolve the
     *complication*
   * GM does a *Mainstream Take*

   *Miss*
   * Play out the scene and the GM writes a *complication*
   * GM does a *Mainstream Take*

** Vigilante Action

   /All protagonists have plot armor!/ They can't die unless their
   player wants them to. This is a game about making the change you
   want to see in the world and what it costs you rather than
   survival.

   When the character is fed up---too frustrated to ignore the
   injustice---they turn to *vigilante action*. Don't plan too
   much. Just go for it. The game and GM are not here to catch you out
   on poor planning.

*** Search and Investigate

    When you look for information about villainous machinations you
    *search and investigate*. This might be patrolling, steakouts,
    asking around, following the money, digging through public records
    or whatever.

    Describe what you want know more about and say what
    kinds of things or places around the city you are looking for and
    what you are doing to look.

    Roll *advantages* against *risk*

    *Strong Hit* Discover what you were looking for. The GM describes
    it and asks questions of the group to help envision it
    * If you looked for the cause of your frustration or for something
      to do about your frustrations, reveal some related villianous
      activities.
    * If you were trying to find out who is behind certain activities
      reveal which villain and which of their resrouces is behind it.
    * If you looked for information about what a villain is doing and
      that villain has unrevealed resources, reveal a resource
    * If you looked for information about what a villain is going and
      your approach could reveal a weakness, reveal a weakness

    *Hit*
    * Discover as above
    * GM does a *mainstream take*

    *Miss*
    * The GM *complicates* an *achievement* used for the roll
    * GM does a *mainstream take*

*** Fight

    When you try to weaken or hurt a villain, their resources, their
    plans, their relationships, etc. you *fight* them. This could be
    anything from releasing damaging footage, to destroying their
    warehouse, to beating up their associates. Anything that weakens
    their position.

    State your intent, what weakenss are you trying to create?
    Describe what you are doing to achieve that outcome.

    *Strong Hit* The GM writes a *weakness* for of the villians resources.

    *Hit*
    * *Weaken* as above
    * GM does a *mainstream take*

    *Miss*
    * GM does a *mainstream take*

*** Take Them Out

    When your intent is to shut the villain down for good, either by
    sending them to jail, killing them, or banishing them to an
    alternate dimention you are trying to *take them out*.

    Say what you are trying to do and how you intend to do it. You can
    use both your *acomplishments* and their *weaknesses* to your
    *advantage* as long as you are in a position to take advantage of
    them.

    Roll *advantage* against *risk* + their *resources*

    *Strong Hit* You take them out. This *villainous machination* is
    complete and resolved. Reset your *frustration* to zero

    *Hit*
    * *Take them out* as above but don't reset *frustration*
    * GM does a *mainstream take*

    *Miss*
    * Increase their *resources* by 2
    * GM does a *mainstream take*

*** Hard-Fought Experience

    When you *miss* or *hit* by exactly one---when *your pool* and the
    *opposing pool* have either exactly the same number of hits (5+),
    or *your pool* has exactly one fewer---on a vigilante action move
    you get *hard-fought experience*

    Roll 3 against 2

    *Strong Hit* Write an *acomplishment* about what you learned. It
    should relate to what you were doing when you learned

    *Hit* As above, but the GM also *complicates* it

** Mainstream Take

   The GM works with the players to frame a scene that will highlight
   the *mainstream take* on what just happened. It may be related
   specifically to the story or it may be an unrelated vignette making
   the point. This is a good place to give the players some direction.
   The mechanical result depends on what just happened and is up to
   the GM to determine though they should discuss what makes sense to
   the players. Use the city beuraucrats and reporters you've already
   created to as a focus for the scene and spew pulp, grit, and camp.

   * If the character was avoiding the injustice in the
     system increase *frustration*
   * If the character is threatening the mainstream values or
     threatening the villains that are enabled by mainstream values
     increase *risk*
   * If the character used an *accomplishment* to their advantage
     outside of normal expectations (friends will help to a point, a
     given level of income can afford so much etc.) *complcate* that
     *accomplishment*
   * If they've been left alone, advance the villain's plans

** Villainous Machinations

**** How Villains are Revealed

     Villains are revealed through play and they could always have
     more resources that haven't been discovered yet. As a GM don't
     decide how powerful a villain is, just let the play progress and
     let the dice and the course of play determine their power. Use
     the foci and especially the discussion about the mainstream
     values guide what you reveal when *the villains do their work*

*** The Villains Do Their Work

    The GM describes evidence of *villainous machinations* and the
    manuvering of the city's systems of injustice. Use the city
    beuraucrats and media you've created to spew pulp, grit, and camp

    The GM chooses a relevant *villainous machination* to progress.

    Increase risk
    A villain gets or expands a resource
    a villain resolves a weakness

**** Create a Villain

     Envision a villain, a paragon of one of the mainstream values not
     shared by any protagonist. Write them a few resources. Spew pulp,
     grit, and camp


