+++
title = "Life Vigilante"
subtitle = "What will you risk to fight for justice"
date = 2020-04-21T08:11:12-05:00
draft = true
categories = [
  "Micro Games",
]
+++

The object of the game is to become attached to the life you've built
then complicate or lose it to fight injustice. The object of the game
is to get a lot to lose, and lose it to uphold your convictions.

Play to find out what they accomplish in their lives, what change they
make to society, and what they give up to do it.

* Set up
** Protagonist

   All players except the Game Master (GM) create a protagonist
   character that they'll play and be responsible for through their
   whole story. To create a protagonist, follow the Life and Vigilante
   sections below.

*** Life

    Write about your real life. Choose a /Real Name/. Write a few *life
    goals*. Make them things you really care about. Things that would
    be tragic to give up. For example: "Start a family" or "Build a
    rewarding career". Write your starting acomplishments and keep
    track of your *frustration* level starting at the number of
    acomplishments you've written.

*** Vigilante

    Write about your secret identity. Choose an /alias/ and describe
    your /costume/. Write a few *convictions*. Make them things you
    really care about. Things you would be willing to risk your life to
    defend and uphold. Write one vigilante thing you've done to uphold
    one of your *Convicions*. Don't make it too risky. Keep track of
    your *Risk* level starting at 1

** Systems of Injustice

   The GM plays everything other than the protagonists. They'll set the
   scene, and challenge the protagonists. They'll respond as the city
   and its systems of injustice manuvering to maintain their power and
   privilege.

   The GM, collaborating with the rest of the group, creates the
   setting. They write about the city and its systems of injustice.
   Discuss this with the group and make sure everyone is cool with the
   city and especially the systems of injustice y'all are going to be
   exploring.  If someone's not into it /for any reason/ it's not going
   to make for a very good game. /Life Vigilante/ gets one thousand
   times better when everyone is on the same page about the systems of
   injustice you'll be exploring and fighting against.

   Name the *City* the *mayor* and the *cheif of police*. Name an
   *investigative reporter*, a *tabloid reporter* and a *pop culture
   influencer*. Use these as foci for envisioning the city and its
   systems of injustice. Feel free to name some more as you find use
   for more throughout play. Drown them in pulp, grit, and slime.

   Write six *mainstream values* that maintain the systems of
   injustice.


*** Villainous Machinations

  Write two to six *mainstream values* that maintain the systems of
  injustice.


* Play by the Rules

  Discuss the *mainstream values* with the group. How do they turn
  people to villainy? What villainous behaviors do they allow to
  flourish? How do they turn people villainous? How do alraeady
  villianous people take advantage? Note down some of these ideas
  with the rest of the foci for the group to refer back to and for
  the GM to use as inspiration when establishing villains and their
  machinations when the truth of the narrative demands.

* The Rules

  Play occurs in one of three modes. *Real Messy Life*, *Vigilante
  Action* or *Media Takes*. Start wherever you have a vision of and
  follow the rules for the mode. They will tell you how to play it and
  how to transition to the others.

** The Dice

   The various rules will sometimes tell you to /roll *advantages*
   against a stat./ That means to assemble two handfulls of dice---use
   different color dice for each pool but always use six sided
   dice. One is for the stat you are rolling against and is a number
   of dice equal to the stat. The other is yours and it's one die for
   each *accomplishment* you are using to your *advantage* in the
   situation. Only use *accomplishments* you can reasonably justify as
   advantagous. Roll them both. If your dice show more fives and sixes
   than what you are rolling against you got a *hit*, if it has more
   than twice as many, you got a *strong hit*. Otherwise you *missed*.

   *Acomplishments* can only be used for advantage if they don't have
   a *complication*

*** Acomplishments

    Things protagonists have achieved working towards their *life
    goals* are written on their character sheet as *acomplishments*
    and are the source of advantage for rolls. Each protagonist writes
    some during character creation.

    For example, *acomplishments* for /Start a Family/ could be:
    * Built a stable partnerhsip with Alex
    * Took a job as a lawyer at Noether and Nash
    * Got a 30 year mortgage on a three bedroom in Parkwood Heights

    *Acomplishments* can be repeated or expanded, keep track of how
    many times this has happened. They can have that many
    complications, and can add up to that many dice to pools when used
    for *advantage*. For example you could mark multiple
    *acomplishments* on the mortgage to represent paying it down or
    mark multiple *acomplishments* on the job to represent
    promotions. Choose whatever makes sense to the fiction.

*** Complications

    Things that get in the way of progress towards *life goals* and
    that make it impossible to use your acomplishments to your
    advantage. They keep you from using the *complicated*
    *accomplishment* as *advantage* in rolls. When an *accomplishment*
    gets *complicated* write the *complication* next to the
    *acomplishment*.

    For example:
    * A mortgage is complicated by a lien or a cracked foundation.
    * A job is complicated by poor performance reviews

** Real Messy Life Scenes

   TODO consider something like a For the Queen deck to draw and
   answer from for every scene

*** Period of Self Reflection

    Choose one:
    * Write a new *life goal*
    * Complete an existing *life goal*
    * Abandon an existing *life goal*

    Say why and how this change of goals will be better for your
    life. roll *advantages* against
    *frustration*.

    Make the change to the goals no matter what the results of the dice.

    *Strong Hit* No ill effect. This period was quick and efficient

    *Hit* You figured it out, but it was troublesome. GM does a *media
    take*

    *Miss* We can't always see what we need to in ourselves. The GM
    *complicates* your next *advancement* (make a note) and does a
    **media take*

*** Get Your Shit Together

    Say what *complication* you want to resolve and how you plan to
    resolve it. roll *advantages*
    against *frustration*

    *Strong Hit*: Resolve it. Remove the *complication*

    *Hit*: Both effects of a *hit* and a *miss*

    *Miss*: GM does a *media take*

*** Deepen a Personal Connection

    Name a character with whome you want to *deepen a personal
    connection*. Then with their player's consent (or the GM's consent
    if they are not a progatonist) narrate or play a scene that leaves
    both characters with a deeper personal connection. Start that
    scene by framing it with a leading question like "How do the two
    of us come to trust each other?" or "How do we fall in love?".
    Check in and make sure everyone is enthusiastic about the
    direction the question leads and change it if someone is not.

    roll *advantages* against *Frustration*. If the character you
    named is a protagonist, they may also roll their *advantages*
    against their *Frustration*

    *Strong Hit* Write an *acomplishment* gaining a friend,
    lover, ally, confidant, etc. Name the other in the acomplishment.

    *Hit* Write an *acomplishment* as above but also write a
    *complication* arising from it.

    *Miss* GM does a *media take*

*** Invest in Yourself

    Say how you are investing in yourself. What are you studying? What
    are you training to do? What are you doing for your career?
    Remember that this can be a flashback to introduce past
    acomplishments you want to bring into the game if that makes more
    sense for the story.

    Roll *advantages* against *frustration*

    *Strong Hit* The time you took to pays off. Write an *acomplishment*
    related to what you did

    *Hit* It pays off as above, but it took a long time. The GM does a
    *media take*

    *Miss* It does not pay off. Don't write an *acomplishment* but it
    did take time so the GM does a *media take*

*** Make Something

    Make something (or if you've got more money than time and
    aptitude, make a purchase) Say what you want to have like a home,
    business, or some other investment. Make it realistic given the
    conceit of your narrative.  If it's something big like a home, you
    can break it up into multiple scenes by starting small and
    expanding it over time (or taking out a loan or mortgage and
    paying over time).

    Roll *advantages* against *Frustration*

    *Strong Hit* You made the thing. Write an acomplishment.

    *Hit* You made it as above, but it was troublesome. *See the
    injustice in the system*

    *Miss* You don't get the thing but the GM does a *media take*

** Vigilante Action Moves

   /All protagonists have plot armor!/ They can't die unless their
   player wants them to. This is a game about making the change you
   want to see in the world and what it costs you rather than
   survival.

   roll *advantages* against Risk, defeat villains, slow or stop their fronts,
   create complications

   TODO Consider earning ranks in action moves when you use them at
   the edge of your ability, these could be written as acomplishments
   like "got good at sweeping the city" though we might want to narrow
   that down to something specific to the way they swept it like "by
   following the money" or "by doing patrolls"

*** Learn From Your Failures

    When you roll a *miss* on a vigilante action move, *learn from
    your failures*

    Roll 2 against 1

    *Strong Hit* Write an *acomplishment* about what you learned. It
    should relate to what you were trying to do when you rolled the
    miss that caused this move

    *Hit* As above, but the GM also *complicates* it

*** Search and Investigate

   When you want to uncover some villainy or expand on some villainy
   you already know about you *search and investigate*. This might be
   patrolling, steakouts, asking around, following the money, or
   whatever. Choose one of the *mainstream values* that frustrates you
   or some villains you want to look into and say what kinds of things
   or places around the city you are looking for and what you are
   doing to look

   Roll *advantages* against *risk*

   *Strong Hit* Discover what you were looking for. The GM describes
   it and asks questions of the group to help envision it

   *Hit* Discover as above, but the GM complcates an *achievement*
   that was used for *advantage* in the roll

   *Miss*
   * The GM *complicates* an *achievement* used for the roll
   * Increase *risk* by one

*** Fight

    When you try to weaken a villain who is resisting and trying to
    weaken you too that's a *fight*. It can be done physically,
    phychologically, emotionally, finantially, etc. Say how you are
    fighting them and state the weakened position you want to put them
    in. If you want to deal with them permenantly you are *taking them
    out* instead

    *Strong Hit* Write a *weakness* for the villain describing the
    position you put them in

    *Hit*
    * Write the *weakness* as above.
    * The GM *complicates* and *achievement* used for the roll.

    *Miss*
    * The GM *complicates* and *achievement* used for the roll.
    * *The villains do their work*

*** Take Them Out

    Finish a section of a front increase risk, complicate, write
    accomplishment like "drove off drunken assholes" or "killed the
    kingpin"

    When you think a villain is weak enough *take them out*

    Roll *advantages* against *risk* + (*resiliance* - *weaknesses*)

    *Strong Hit*
    * Reset *frustration* to zero
    * Mark the villain's number of *resources* against a *mainstream
      value* that the villain represented. If there are more than 10
      marked, replace the *mainstream value* with any of your
      convictions. Any progatonist may take this conviction

    *Hit* As above but don't reset *frustration*

    *Miss*
    * Increase *risk* by one
    * *The villains do their work*
    * *See the system for what it is*

  Notes:
  * This is a roll to try and defeat a villain and "complete the front"
  * If it succeeds you make an amount of progress towards changing the
    system equal to their resources
  * It should be hard to get enough ahead of a villains resources to make
    this roll easy wihtout a lot of work.

** Mainstream Takes

*** See the System for What it is

    Roll the number of convictions you share with mainstream values
    against 1

    *Strong Hit* Discuss and celebrate the change you've made to the
    system. Reset *frustration* to zero.

    *Hit* Discuss and celebrate the change you've made to the system

    *Miss* The GM describes the injustice that the players see
    inherent in the system. This could be related to the scene that
    it's associated with, or it could be a transitional vignette. Use
    the city beuraucrats and reporters you've already created to spew
    pulp, grit, and slime.

    Increase *frustration*
    Remember to note specific details of the villains as they are
    revealed and described. Name them when appropriate, describe and
    write down all of the *resources* that have been revealed and
    described.

**** How Villains are Revealed

     Villains are revealed through play they could always have more
     resources that haven't been discovered yet. As a GM don't decide
     how powerful a villain is, just let the play progress and let the
     dice and the course of play determine their power. Use the foci
     and especially the discussion about the mainstream values guide
     what you reveal when *the villains do their work*

*** See the Change You've Made

*** The Villains Do Their Work

    The GM describes evidence of *villainous machinations* and the
    manuvering of the city's systems of injustice. Use the city
    beuraucrats and media you've created to spew pulp, grit, and slime

    The GM chooses a relevant *villainous machination* to progress.

    Increase risk
    A villain gets or expands a resource
    a villain resolves a weakness

**** Create a Villain

     Envision a villain, a paragon of one of the mainstream values not
     shared by any protagonist. Write them a few resources. Spew pulp,
     grit, and slime


