+++ag
title = "Life Vigilante"
subtitle = "What will you risk to fight for justice"
date = 2020-04-21T08:11:12-05:00
draft = true
categories = [
  "Micro Games",
]
+++

Play to find out what they accomplish in their lives, what change they
make to society, and what they give up to do it.

* Protagonist

  All players except the Game Master (GM) create a protagonist
  character that they'll play and be responsible for through their
  whole story. To create a protagonist, follow the Life and Vigilante
  sections below.

** Life

   Write about your real life. Choose a /Real Name/. Write a few *life
   goals*. Make them things you really care about. Things that would
   be tragic to give up. For example: "Start a family" or "Build a
   rewarding career". Write your starting acomplishments and keep
   track of your *frustration* level starting at three.

** Vigilante

   Write about your secret identity. Choose an /alias/ and describe
   your /costume/. Write a few *convictions*. Make them things you
   really care about. Things you would be willing to risk your life to
   defend and uphold. Write one vigilante thing you've done to uphold
   one of your *Convicions*. Don't make it too risky. Keep track of
   your *Risk* level starting at 1

* Systems of Injustice

  The GM plays everything other than the protagonists. They'll set the
  scene, and challenge the protagonists. They'll respond as the city
  and its systems of injustice manuvering to maintain their power and
  privilege.

  The GM, collaborating with the rest of the group, creates the
  setting. They write about the city and its systems of injustice.
  Discuss this with the group and make sure everyone is cool with the
  city and especially the systems of injustice y'all are going to be
  exploring.  If someone's not into it /for any reason/ it's not going
  to make for a very good game. /Life Vigilante/ gets one thousand
  times better when everyone is on the same page about the systems of
  injustice you'll be exploring and fighting against.

  Name the *City* the *mayor* and the *cheif of police*. Name an
  *investigative reporter*, a *tabloid reporter* and a *pop culture
  influencer*. Use these as foci for envisioning the city and its
  systems of injustice. Feel free to name some more as you find use
  for more throughout play. Drown them in pulp, grit, and slime.

  Write six *mainstream values* that maintain the systems of
  injustice.

** Villainous Machinations

* The Rules

  Play occurs in one of three modes. *Real Messy Life*, *Vigilante
  Action* or *Media Takes*. Start wherever you have a vision of and
  follow the rules for the mode. They will tell you how to play it and
  how to transition to the others.

** The Dice

   The various rules will sometimes tell you to "roll against a stat."
   That means to assemble two handfulls of dice (use different color
   dice for each pool but always use six sided dice). One the size of
   the stat you are rolling against. The other is yours and it's one
   die for each *accomplishment* you are using for *advantage* in the
   roll. Only use *accomplishments* you can reasonably justify as
   advantagous. Roll them both. If your dice show more fives and sixes
   than what you are rolling against you got a *hit*, if it has more
   than twice as many, you got a *strong hit*. Otherwise you *missed*.

   *Acomplishments* can only be used for advantage if they don't have
   a *impediment*

*** Acomplishments

    Things protagonists have achieved working towards their *life
    goals*. Each protagonist writes some during character creation.
    When you make an acomplishment, write it on your sheet.

    For example, *acomplishments* for "Start a Family" could be:
    * Got into a long term committed relationship with Alex
    * Took a stable job as a lawyer at Noether and Nash
    * Took out a 30 year mortgage on a three bedroom home in Parkwood
      Heights

    Some *acomplishments* can be repeated or expanded, keep track of
    how many times this has happened. They can have that many
    complications, and can add up to that many dice to pools when used
    for *advantage*. For example you could mark multiple
    *acomplishments* on the mortgage to represent paying it down or
    mark multiple *acomplishments* on the job to represent
    promotions. Choose whatever makes sense to the fiction.

*** Impediments

    Things that get in the way of progress towards *life goals*. They
    must be resolved before making more progress on any goal and keep
    you from using the impeded *accomplishment* as *advantage* in
    rolls. When an *accomplishment* gets impeded write the
    *impediment* next to the *acomplishment*.

    For example:
    * A mortgage might be impeded by a lien or a cracked
      foundation.
    * A job might be impeded by poor performance reviews or a
      performance improvement program

** Real Messy Life Scenes

   When a scene calls for you to draw and answer the question, either
   draw a card from the *Real Messy Life* deck or draw from a standard
   deck of cards and look up the question in the tables. Cards in the
   inclued deck have one question for each of these scenes. When you
   draw, answer the question that matches the scene.

*** Period of Self Reflection

    Choose one:
    * Write a new *life goal*
    * Complete an existing *life goal*
    * Abandon an existing *life goal*

    Say why and how this change of goals will be better for your
    life. Draw and answer the question. Roll against *Frustration*.

    Make the change to the goals no matter what the results of the dice.

    *Strong Hit*: No ill effect. This period was quick and efficient

    *Hit*: It took some time to figure this out, *See the Injustice in
    the System*

    *Miss*: We can't always see what we need to in ourselves. The GM
    complicates your next advancement and you *See the Injustice in
    the System*

*** Get Your Shit Together

    Say what complication you want to resolve and how you plan to
    resolve it. Draw and answer the question. Roll against
    *Frustration*

    *Strong Hit*: Resolve it

    *Hit*: Both effects of a Hit and a Miss

    *Miss*: GM chooses one.
    * *See the Injustice in the System*
    * *The Villains Do Their Work*

*** Deepen a Personal Connection

    Name a character with whome you want to *deepen a personal
    connection*. Then with their player's consent (or the GM's consent
    if they are not a progatonist) narrate or play a scene that leaves
    both characters with a deeper personal connection. Start that
    scene by framing it with a leading question like "How do the two
    of us come to trust each other?" or "How do we fall in love?".
    Check in and make sure everyone is enthusiastic about the
    direction the question leads and change it if someone is not.

    Roll against *Frustration*. If the character you named is a
    protagonist, they may also roll against their *Frustration*

    *Strong Hit* Write an acomplishment gaining a friend,
    lover, ally, confidant, etc. Name the other in the acomplishment.

    *Hit* Write an acomplishment as above but also write a
    complication arising from it.

    *Miss* *See the Injustice in the System*

*** Invest in Yourself

    Say how you are investing in yourself. What are you studying? What
    are you training to do? What are you doing for your career?
    Remember that this can be a flashback to introduce past
    acomplishments you want to bring into the game if that makes more
    sense for the story.

    Draw and answer the question then Roll against *Frustration*

    *Strong Hit* The time you took to *invest in yourself* pays off,
    write an acomplishment related to what you did and your answer to
    the question

    *Hit* It pays off as above, but it took a long time. *The Villains
    Do Their Work*

    *Miss* It does not pay off, don't write an *acomplishment* but it
    did take time so *The Villains Do Their Work*

*** Make a Purchase

    Say what you are buying like a home, business, or some other
    investment. Make it realistic given the conceit of your narrative.
    If you are buying something big like a home, you can break it up
    into multiple scenes by taking out a mortgage for example.

    Draw and answer the question then Roll against *Frustration*

    *Strong Hit* You get the thing

    *Hit* You get the thing and you *see the injustice in the system*

    *Miss* You don't get the thing but you do *see the injustice in
    the system*

** Vigilante Action Moves

   All protagonists have plot armor, meaning they can't die unless
   their player wants them to. This is a game about making the change
   you want to see in the world not about survival.

   Roll against Risk, defeat villains, slow or stop their fronts,
   create complications

*** Sweep the City

   When you want to uncover some villainy in the city to try to do
   something about *sweep the city*. Choose one of the *mainstream
   values* that frustrates you and say what kinds of things or places
   around the city you are looking for and what you are doing to look

   Roll *Frustration* against *Risk*

   *Strong Hit* Discover what you were looking for. The GM describes
   it and asks questions of the group to help envision it

   *Hit* Discover as above, but the GM complcates an *achievement*
   that was used for *advantage* in the roll

   *Miss* the GM complicates an *achievement* used for the roll,
   increase *risk* by one

*** Follow the Money

    When you are trying to find out information on a villain's
    activities or associations you can *follow the money*. Describe
    what you want to know and what you are looking into to find out.

    Roll against Risk

    *Strong Hit* You find what you are looking for. The GM describes
    what you've found.

    *Hit* Find what you are looking for as above, but the GM
    complicates an *achievement* that was used for *advantage* in the
    roll

    *Miss* The GM Complicates an *achievement* used for the roll and
    increases *risk* by one

*** Find the Motherfucker

*** Get in the Ring

*** Finish It Once and For All

** Mainstream Takes
*** See the Injustice in the System

   The GM describes the injustice that the players see inherent in the
   system. This could be related to the scene that it's associated
   with, or it could be a transitional vignette. Use the city
   beuraucrats and reporters you've already created to spew pulp,
   grit, and slime.

   Increase *Frustration* by one for the protagonist(s) the scene was
   about

*** The Villains Do Their Work

    The GM describes evidence of *villainous machinations* and the
    manuvering of the city's systems of injustice. Use the city
    beuraucrats and media you've created to spew pulp, grit, and slime

    The GM chooses a relevant *villainous machination* and *progresses*

*** See the Change You've Made

    When you think you've resolved one of the *villainous
    machinations* you may *see the change you've made*

    Roll

    Reset *frustration* to zero

    Remove the *mainstream value* associated with the *villainous
    machination* and replace it with one of your convictions. Decide
    if it should act as the focus of a new *villainous machincation*

** Villainous Machinations

   No prep lazily evaluated fronts

   Each of the original *mainstream values* acts as the focus of a
   *Villainous Machination*

*** Create a Machination
*** Progress a Machination
