+++
title = "Quill"
version = "0.2.0-draft"
subtitle = ""
date = 2020-05-22T07:44:45-05:00
draft = true
categories = [
  "Games",
]
+++

I'm assuming that you are familiar with classic and OSR role playing
games. Quill won't explain much of what is common to them so If you
are new to roleplaying, I hope a little internet research will clear
anything up. If not please let me know either on Twitter
(@jessebmiller), through email <jesse@jessebmiller.com> or on the
[Porcupine Studio chat](chat.porcupine.studio) (Discord at the time of
this writing).

Quill was influenced by a bunch of great prior work.

*Dungeons & Dragons* by Wizards of the Coast.

*Blades in the Dark* by John Harper

*Apocalypse World* by Meguey and D. Vincent Baker

Thank you for the path you blazed!

The object of Quill is to become powerful by the experience of
dangerous adventure but you might not because the danger is real and
you could fucking die.

* Design Goals

  - *Oppinionated*. Strong choices for a focused audience
  - *Minimal quick math* Move as many calculations out of the flow of
    play and into character creation or session downtime
  - *Simple rule set* Minimal cross references and look ups,
    especially during the flow of play.
  - *Large design space* Support hacking and custom content.
  - *Efficient expert execution* Once a group masters the system, they
    all should easily maintain continuity and agreement the whole of
    the fiction
  - *Enjoyable* Even groups that haven't yet mastered the system
    should none the less enjoy their time playing.
  - *Rules that drive the game* Rules should always drive the goals of
    the game, and may take players out of their characters to do so.
  - *Consiceness* It should be a small core ruleset that fits in a
    small book. Expansions should fit in similarly small books.

* Safety

  At the beginning of every session, mention the X card, and ask if
  anyone has any lines or veils they want to have in place for the
  session. Something freeing and great happens when the game is safe
  and everyone knows what lines not to cross and trusts that everyone
  can speak up if something makes them uncomfortable trusting that the
  group will change it without judgment. Everyone can go a little
  deeper safe in the knowledge that if they go too far someone will
  speak up and everyone will step back and change it.

* Talents

  It's a tabletop role playing game so once the group has read this
  through, followed the instructions, and made some characters (PCs),
  the game master (GM) will describe the situation and the players
  will say what they do. And on and on it goes until someone does
  something that might fail.

  Quill PCs have *talents* representing the difficult and powerful
  things they can do that might fail. PCs improve at *Talents* by
  earning and spending *experience* on their talents. Things like
  attacking with a particular weapon, perception, intimidation,
  casting wizard, cleric, or other spells, sneak attacks, and even
  keeping animal companions are all *talents*. How capable a PC is at
  each *talent* is represented by a die size. They all start at d4 and
  can progress with *experience* through the other die sizes (d6, d8,
  d10, d12 and d20).

** Talent Checks

   When a PC does something that is a *talent*, like attacking with a
   weapon, intimidating someone, or casting a spell, roll a check. The
   *talent* specifies an *ability* to use and the GM determines a
   difficulty based on the fictional situation. The player rolls their
   die for that *talent*. If they roll under the difficulty, that's a
   *miss*. If they roll over the *ability* that's a *bust* (it can be
   both). Otherwise it's a *hit*

   The outcomes of talent checks, especially the consequences for
   *misses* and *busts*, are what drive the game forward.

   *Hit*: the player narrates their success

   *Miss*: the GM narrates the complication, setback, or obstacle that
   the failure causes. If the talent doesn't specify anything, invent
   something relevant to the situation.

   *Bust*: the GM narrates what the talent specifies or narrates a
   partial, incomplete, or fatally flawed success and possibly also a
   complication, setback, or obstacle it causes. A *bust* shouldn't be
   as bad as a *miss*.

   The following shows roughly what each *talent* die level represents
   along with rough guidance for the GM to determine a check's
   difficulty

   | Talent Die Level | Rough Level of Experience | Challenging  Difficulty | Impossible Difficulty |
   |------------------+---------------------------+-------------------------+-----------------------|
   | d4               | No training               |                       2 |                     5 |
   | d6               | Some training             |                       3 |                     7 |
   | d8               | Well trained              |                       4 |                     9 |
   | d10              | Expert                    |                       5 |                    11 |
   | d12              | Expert Specialist         |                       6 |                    13 |
   | d20              | Godlike                   |                      10 |                    21 |

** Advantage and Disadvantage

   Some rules grant you *advantage* or give you *disadvantage*. When
   you have *advantage* roll 2 dice and take the better die. When you
   have *disadvantage* roll 2 and take the worse. A *hit* is better
   than *bust* is better than *miss*

** Related Talents

   Talent in one area grants some capability in related areas.
   *Talents* are related to *talents* with a matching tag specified in
   their description, the *talent* name counts as one of these
   tags. Whatever die you have in a talent, you've got one level lower
   in all related talents.

   For example: The following *talents* are related to each
   other. Therefore if you've got a d10 in *javelin* you've got at least
   a d8 in *spear* and *pike* for free.

   *spear* TODO write spear

   *javelin* (spear) TODO write javelin

   *pike* (spear, pole-arm) TODO write pike

** Talent Lists

   Talents are organized into lists, each with common rules and
   defaults that apply to everything in the list. Lists may have
   sub-lists that further organize talents. Talents in sub-lists have
   all the rules of the lists as usual and the rules of the list that
   contains them. The full lists are found in the Appendix (p. ???)
   and each are described with their general rules below.

   The lists are:
   - Skills
     - Crafting
   - Gear
     - Weapons
     - Armor
   - Spells
     - Wizard
     - Cleric

** Skills

   The most basic *talents* are skills. The classics like *athletics*,
   *intimidate* and *perception* as well as what might traditionally
   be class features like *sneak attack*, *divine smite*, and *bardic
   inspiration* are skills in Quill. They are listed in Appendix B
   (p. ???) and include everything you need in one description that
   will specify at least the effect of a *hit* and the *ability* for
   its use and may specify more like what happens on a *miss* or a
   *bust* (see p. ??? for defaults), a minimum difficulty (default 0),
   related *talents* (it's always related to its own name), an
   *ability* for advancement (see p. ??? for details)

** Gear

   PCs have easy access to regular mundane necessities unless
   otherwise noted. A rule or the fiction could deny access, in which
   case follow the rule or make a ruling as appropriate to the
   fiction. Otherwise items are gear *gear* and a *talent*. The
   descriptions of specific *gear* will give you everything you need
   to make checks for their use.

   There will probably be some money system to deal with the cost of
   gear but for now just make something up based on the fiction.

*** Weapons

    Weapons are a specific kind of gear so all gear rules apply as
    well as the following general rules for all weapons
    - When you attack a target with a weapon roll a check where the
      difficulty is the targets *DEF*. On a *hit* deal damage as
      rolled.
    - The weapon description will include the stat to use
    - Weapons may have properties that specify more details outlined
      below.
    - Weapons can only choose targets melee range (roughly 1.5 meters
      or 5 feet) by default.

    Specific weapons are listed in the Appendix (p. ???)

**** Properties

     *Range* Ranged weapons can attack within their listed range
     without penalty. For every 10 feet beyond their range however;
     their target gets +1 *DEF*. For example: attacking someone 50
     feet away with a weapon that has *range 20* grants the target *+3
     DEF*.

     *Reach* Weapons with reach can attack 5 to 10 feet away without
     penalty but targets within 5 feet gain 2 *DEF*.

     *Conceal* In order to notice these when concealed by the wielder
     an observer must *hit* a perception check against 6. They must be
      removed from concealment for use however.

     *Charge* Charging a target doubles the number of wounds and stress
     caused by the attack. Charging is moving more than half your
     movement in a round in a straight line towards the target.

     *Brace* Doubles wounds and stress caused by an attack if the
     weapon is braced on the ground---or other steady object like a tree
     or a wall---against a charging opponent.

     *Mount* Mount weapons can be used without penalty while riding a
     mount but all targets gain 2 *DEF* when wielded on foot. If a
     specific mount is noted, for example *horse mount* or *dragon
     mount* the penalty applies any time the wielder is no on the
     specified mount.

     *Mounted charge* See *charge* but only apply to bonus if the
     wielder is mounted. A specific mount may be required as per
     *mount*.

     *Formation* Attack with no penalty when used by an individual or
     coordinated group who are in formation and do not have more
     enemies focused on and able to attack them than they do have
     adjacent formation members. Their targets gain *+2 DEF*
     otherwise. For example: a group of 2 in formation with pikes side
     by side against 3 attackers on foot attack as normal if the
     attackers are each focused on one pike wielder. However if the 2
     attackers move to one side of the formation and attack one of the
     pike wielders on the end they gain *+2 DEF*.

*** Armor

    This is a special case because *armor*, once made and worn, does
    not take talent to be effective. When worn you gain the amount of
    *armor* in its description.
** Spells

   Anyone can learn magic. You don't have to be a Wizard or anything.
   If you decide to learn to cast wizard spells you're a fucking
   wizard. You can learn spells from any spell list. If you pleased a
   god and were granted a cleric spell, you're also a fucking cleric.
   In fact, because the default die for every *talent* is a d4
   everyone starts out able to cast all spells, just not very well and
   they'll probably fail because...

   All spells have a *spell level* (1-9) and have a minimum difficulty
   of their level + 3. Go ahead, Try casting wish with your default
   d4, you'll *miss* and it'll backfire on you bad.

   Spells have failure tables for their *misses*. When you *miss* a
   spell check, look up the effect of your die roll on the table in
   the spell's description, or the default table below if the spell
   doesn't have a listing for your roll. In addition take the spell
   level in stress.

   | Roll | Default Miss Effect                                         |
   |------+-------------------------------------------------------------|
   |    1 | The caster is struck by astral lightning. Make a *STR*      |
   |      | save against *torn muscles*                                 |
   |------+-------------------------------------------------------------|
   |    2 | A pit 20 feet deep opens up below the caster who falls      |
   |      | in. Make a *DEX* save against *broken bones*.               |
   |------+-------------------------------------------------------------|
   |    3 | Shadow spiders are summoned and begin nesting in the        |
   |      | caster's gut. Make a *CON* save against *internal bleeding* |
   |------+-------------------------------------------------------------|
   |    4 | The Caster's mind is wracked by unnatural concussion.       |
   |      | Make a *INT* save against *Delirious Confusion              |
   |------+-------------------------------------------------------------|
   |    5 | The caster is overcome with terrors. Make a *WIS* save      |
   |      | against *delirious confusion*.                              |
   |------+-------------------------------------------------------------|
   |    6 | The caster sees a vision of their own weakness. Make a      |
   |      | *CHA* save against *wounded pride*                          |
   |------+-------------------------------------------------------------|
   |    7 | The caster is flung about violently. Take a wound.          |
   |------+-------------------------------------------------------------|
   |    8 | The caster is engulfed in a flash of magic flame. Take      |
   |      | a wound                                                     |
   |------+-------------------------------------------------------------|
   |    9 | All the caster's organs vanish for an instant. Take a       |
   |      | wound.                                                      |
   |------+-------------------------------------------------------------|
   |   10 | An angered angel crushes the caster with shame. Take two    |
   |      | wounds                                                      |
   |------+-------------------------------------------------------------|
   |   11 | An eager demon touches the caster's heart. Take two wounds. |
   |------+-------------------------------------------------------------|
   |   12 | An vengeful god reveals the casters weakness to all         |
   |      | present. Take *wounded pride* then make three *CHA*         |
   |      | saves against one wound each.                               |

   Spell lists and descriptions can be found in the Appendix

* Adventuring
** Creating Characters

   Quill characters are very easy to create.

   1. Roll 1d6+4 six times and distribute the results to the 6
      *abilities*.
   2. Distribute this array of dice [d10, d8, d8, d6, d6, d6] to any
      *talents* you'd like to start with. Remember all PCs can use any
      *talent* at d4
   3. Take as much *gear* as you want to start the game carrying on
      you
   4. Complete the remaining calculations on the character sheet. Make
      a copy of this spreadsheet or follow its calculations on a sheet
      of paper
      https://docs.google.com/spreadsheets/d/1Kk8qv-6OAniIrIJ5gkK1HLH9N-pHM04qMQi9lM2Juhk/edit?usp=sharing
      Don't worry... there will be a real character sheet some day,
      it's just too early in development right now.

** Stress

   When stress is greater than your third highest ability score you
   take 1d6 - 1 wounds and pass out for 20 minutes or until attended
   to for at least 1 minute. Upon waking you must immediately take a
   short rest (which means eat and drink) or pass out again.

*** Pushing

    You can push yourself on any check and take as many of the
    following as you want as many times as you want but declare it all
    before you roll the check.

    - take 1d6 -1 stress and gain advantage or lose disadvantage
      (take this twice to go from disadvantage to advantage)
    - take 1d6 -1 stress and roll 1 die level higher
    - take 1d8 -1 stress and roll 2 die levels higher
    - take 1d10 -1 stress and roll 3 die levels higher
    - take 1d4 -1 stress and reduce the difficulty by 1
    - take 1d4 -1 stress and increase your effective ability score by 1
     for this check
    - take 1d12 -1 stress to get an automatic *hit*
    - take 1d10 -1 stress to get an automatic *bust*

*** Resisting

    After you roll you can resist the consequence of a *bust* or a
    *miss* by paying stress. Narrate how you are avoiding it then roll
    to see how much stress you take to do it.

    take 1dx -1 *stress* where x is the same die you rolled for a
    *miss* and one level lower for a *bust* to a minimum of 4.

** Wounds and Death

   For every wound you take, mark one of the unmarked wound boxes on
   your character sheet. Each one comes with it's own particular
   drawback. When all wounds are marked you die.

*** The Six Wounds

    - *Torn Muscles*: Make checks with effective *STR* of 4
    - *Broken Bones*: Make checks with effective *DEX* of 4
    - *Internal Bleeding*: Make checks with effective *CON* of 4
    - *Delirious Confusion*: Make checks with effective *INT* of 4
    - *Traumatic Brain Injury*: Make checks with effective *WIS* of 4
    - *Wounded Pride*: Make checks with effective *CHA* of 4

** Movement

   Your movement is 30 feet and you can hike a number of miles equal
   to *CON* before needing a *short rest*. You can make that hike twice
   before needing a *long rest*.

** Rest and Recovery

   There are *short rests* and *long rests*. Each require you to eat
   half a *load* of food and drink. Short rests take about an
   hour. Long rests take at least 8 hours.

   After a short rest roll xd6 where x is your stress. remove the
   lowest die worth of stress

   After a long rest remove all stress.

   To recover from your wounds, when you start to rest roll xd6 where
   x is the number of wounds you have taken. Rest that many
   consecutive days to recover all your wounds.

* Advancement

  When you *push yourself* and *miss* using a *talent* mark its
  Experience Points (*XP*). Once you've marked enough *XP* in a talent
  you may *advance the talent*.

  When you *push yourself* on an *ability save* and fail mark *ability
  XP*. When you have enough experience from anywhere---you may spend
  experience marked against a *talent* for this---you may *advance an
  ability*.

  Advance only during a long rest.

** Advance the talent

   When you've got enough XP in a *talent* you may *advance the
   talent* to its next highest die by paying an amount of experience
   equal to its max (6, 8, 10, 12, or 20).

   If the *talent* description includes an *ability* "to advance"
   ("*INT* to advance" for example) you need to roll that next highest
   die under the *ability*. If you do, *advance the talent* to that
   next die. If you *bust*, don't advance but do refund yourself an
   amount of experience equal to your roll.

** Advance an Ability Score

   You may *advance an ability score* by one if you pay an amount of
   *XP* equal to the number you are advancing to. Advancing *CON* from
   7 to 8 costs 8 *XP*. You may spend *XP* that was marked against any
   *talent* for this.

* Hacking Quill

  TODO Not needed for the play test, but you should be able to bring
  in spells at least pretty easy. Might need some guidance using
  monster stat blocks or weapons or class features and so on.

* Appendix A: Skills

** Gossip

   *sight* to use

   Roll when you do something that relies on a rumor's veracity that
   you heard through gossip. Players can invent these on the fly.

   *hit* the rumor is true

   *bust* the rumor is true but it's just the tip of the iceberg choose one
   1. you're in over your head
   2. you've tipped your hand and the wrong people now know you were gossiping
   3. you've tipped your sources hand and they are displeased with you

   *miss* the rumor was false or misleading

* Appendix B: Gear
** Weapons
** Armor
* Appendix C: Spell Lists
* Appendix D: Conditions

  Some rules will call for one of these conditions, or will be active
  only during a condition.

** Staggered

   Make a d20 check against the highest of your STR, DEX, and CON
   with the difficulty specified by the rule that called for the
   stagger. For example if the rule said "*stagger 5*", the difficulty
   of the check is 5

   *Miss*: fall prone

   *Bust*: All checks next round have disadvantage

** Prone

   You've fallen to the ground either purposely or otherwise. If you
   were prone this round, attacks against you have advantage if the
   attacker is close, and have disadvantage otherwise. It takes half
   your movement to stand up.

* Appendix E: Monsters and Challenges


