+++
title = "Quill"
version = "0.2.0-draft"
subtitle = ""
date = 2020-05-22T07:44:45-05:00
draft = true
categories = [
  "Games",
]
+++

I'm assuming that you are familiar with role playing games. Quill
won't explain much of what is common to most of them so If you are new
to roleplaying, I hope a little internet research will clear anything
up. If not please let me know either on Twitter (@jessebmiller),
through email <jesse@jessebmiller.com> or on the [Porcupine Studio
chat](chat.porcupine.studio) (Discord at the time of this writing).

Quill was influenced by a bunch of great prior work.

*Dungeons & Dragons* by Wizards of the Coast.

*Blades in the Dark* by John Harper

*Apocalypse World* by Meguey and D. Vincent Baker

Thank you for the path you blazed!

The object of Quill is to become powerful by the experience of
dangerous adventure but you might not because the danger is real and
you could fucking die.

* Design Goals

  - *Oppinionated*. Strong choices for a focused audience
  - *Minimal quick math* Move as many calculations out of the flow of
    play and into character creation or session downtime
  - *Simple rule set* Minimal cross references and look ups,
    especially during the flow of play.
  - *Large design space* Support hacking and custom content.
  - *Efficient expert execution* Once a group masters the system, they
    all should easily maintain continuity and agreement the whole of
    the fiction
  - *Enjoyable* Even groups that haven't yet mastered the system
    should none the less enjoy their time playing.
  - *Rules that drive the game* Rules should always drive the goals of
    the game, and may take players out of their characters to do so.
  - *Consiceness* It should be a small core ruleset that fits in a
    small book. Expansions should fit in similarly small books.

* Safety

  At the beginning of every session, mention the X card, and ask if
  anyone has any lines or veils they want to have in place for the
  session. Something freeing and great happens when the game is safe
  and everyone knows what lines not to cross and trusts that everyone
  can speak up if something makes them uncomfortable trusting that the
  group will change it without judgment. Everyone can go a little
  deeper safe in the knowledge that if they go too far someone will
  speak up and everyone will step back and change it.

* Basic Rules

  These are the core rules that don't require a roll and that talents
  may depend on or affect.

** Rest

   There are *short rests* and *long rests*. Each require you to eat
   and drink. Short rests take about an hour. Long rests take at least
   8 hours.

** Injury and Death

   For every *injury* you suffer, mark one of the unmarked
   *injuries*. When all *injuries* are marked *face death*.

** Recovery

   After a *short rest* recover 1d6 *strain*

   After a *long rest* recover all *strain*.

   After a *long rest* if you have an *injury* to recover roll xd6
   where x is your number of *injuries*. If the highest die is 1-4
   recover one *injury*

   To recover from all your *injuries*, when you start to rest roll xd6
   where x is the number of *injuries* you have taken. Rest that many
   consecutive days to recover all your *injuries*. If someone is
   tending to you roll one fewer dice.

** Strain

   When *strain* is greater than 12 suffer 1d4 injuries and pass out
   for 20 minutes or until attended to for at least 1 minute. Upon
   waking you must immediately take a short rest (which means eat and
   drink) or pass out again.

*** Pushing

    You can push yourself on any check and take as many of the
    following as you want as many times as you want but declare it all
    and take the *strain* before you roll the check.

    - take 1d6 *strain* and gain advantage or lose disadvantage
      (take this twice to go from disadvantage to advantage)
    - take 1d6 *strain* and roll 1 die level higher
    - take 1d8 *strain* and roll 2 die levels higher
    - take 1d10 *strain* and roll 3 die levels higher
    - take 1d4 *strain* and reduce the difficulty by 1
    - take 1d4 *strain* and increase your effective *potential* by 1
    - take 1d12 *strain* to get an automatic *hit*
    - take 1d10 *strain* to get an automatic *bust*

*** Resisting

    After you roll you can resist the consequence of a *bust* or a
    *miss* by paying *strain*. Narrate how you are avoiding it then roll
    to see how much *strain* you take to do it.

    take 1dx *strain* where x is the same die you rolled for a *miss*
    and one level lower for a *bust* to a minimum of 4.

** Flashbacks

   Like Forged in the Dark.

* Talents

  It's a tabletop role playing game so once the group has read this
  through, followed the instructions, and made some characters (PCs),
  the game master (GM) will describe the situation and the players
  will say what they do and the GM will say "okay" or "make a talent
  check" (or "wait, let's clarify the fiction"). And back and forth
  like that.

  Quill PCs have *talents* representing the difficult and powerful
  things they can do that might fail. PCs improve at *Talents* by
  earning and spending *experience* on their talents. Things like
  fighting with a particular weapon, perception, intimidation, casting
  wizard, cleric, or other spells, sneak attacks, and even keeping
  animal companions are all *talents*. How capable a PC is at each
  *talent* is represented by a die size. They all start at d4 and can
  progress with *experience* through the other die sizes (d6, d8, d10,
  d12 and d20).

** Talent Checks

   When a PC does something that is a *talent*, like fighting with a
   weapon, intimidating someone, or casting a spell, roll a check. The
   *talent* specifies a *potential* based on your character sheet and
   the GM determines a *difficulty* based on the fictional situation.
   The player rolls their die for that *talent*. If they roll under
   the *difficulty*, that's a *miss*. If they roll over the
   *potential* that's a *bust* (it can be both). Otherwise it's a
   *hit*. Many talents base *potential* on other talents or even
   themselves. In these cases use the /die size/ you have in the
   talent for *potential*. For example, *Gossip* specifies "The lower
   of *Perception* and *Acquaintances*". Say your *Perception* was
   *d10* and your *Acquaintances* was *d6* your *potential* for
   *Gossip* would be *6*

   The outcomes of talent checks, especially the consequences for
   *misses* and *busts*, are what drive the game forward and unless
   otherwise stated use this as a guide.

   *Hit*: the player narrates their success

   *Miss*: the GM narrates the complication, setback, or obstacle that
   the failure causes. If the talent doesn't specify anything, invent
   something relevant to the situation.

   *Bust*: the GM narrates what the talent specifies or narrates a
   partial, incomplete, or fatally flawed success and possibly also a
   complication, setback, or obstacle it causes. A *bust* shouldn't be
   as bad as a *miss*.

   This table shows roughly what each *talent* die level represents
   along with rough guidance for the GM to determine a check's
   *difficulty*

   | Talent Die | Level of Experience | Challenging | Impossible |
   |------------+---------------------+-------------+------------|
   | d4         | No training         |           2 |          5 |
   | d6         | Some training       |           3 |          7 |
   | d8         | Well trained        |           4 |          9 |
   | d10        | Expert              |           5 |         11 |
   | d12        | Expert Specialist   |           6 |         13 |
   | d20        | Godlike             |          10 |         21 |

** Advantage and Disadvantage

   Some rules grant you *advantage* or give you *disadvantage*. When
   you have *advantage* roll 2 dice and take the better die. When you
   have *disadvantage* roll 2 and take the worse. A *hit* is better
   than *bust* is better than *miss*

* Talent properties

  There are some properties that are named here, and then simply
  referenced in their talent description. Things like range for
  weapons, verbal and somatic components for spells etc.

** Melee

   Potential: *Fight* when used in melee range

** Ranged X Y

   Potential: Lower of *Perception* and *Anticipation* when used
   outside beyond melee range up to X feet. Every Y feet beyond that
   the target gains 1 *defense*

** Reach

   Potential: *Fight* when used in melee range or just outside of
   melee range.

   When you *fight* just beyond melee range with a *reach* weapon you
   can keep one opponent from entering melee range until they find an
   opportunity to close. When you fight with a *reach* weapon in melee
   range you are *disadvantaged*

   The opponent may move into melee range whenever you *miss*. If they
   do you must *quick draw* at *disadvantage* in order switch to a
   melee weapon.

   The opponent may move into melee range whenever you *bust*. If they
   do you must *quick draw* with *advantage* in order to switch to a
   melee weapon.

** Sunder

   When you *bust* in addition to other effects, reduce the target's
   armor by 1

** Finesse

   For the purposes of determining *defense* when fighting with a
   *finesse* weapon treat your number of injuries as one fewer. This
   makes your base unarmored defense 4 with no injuries.

** Flexible

   Can be used either one handed or two handed.

* Creating Characters

  Distribute 2d10, 3d8, and 4d6 to any *talents* you'd like to start
  with. Only one die level per talent. All PCs can use any *talent* at
  d4

  Take as much gear as you want but check with your GM and other
  players first to make sure everyone is happy with it.

  Complete the calculations on your chatacter sheet.

* Advancement

  When you *push yourself* and *miss* using a *talent* mark its
  Experience Points (*XP*). Once you've marked enough *XP* in a talent
  you may advance it to its next highest die by paying an amount of
  experience equal to its rank (6, 8, 10, 12, or 20).

  Advance only during a long rest.

* Appendix A: Talents
** Anticipation

   Potential: *Anticipation* - 4

   Roll when you think you could have *anticipated* something. Say how
   you anticipated it and how you are prepared.

** Acquaintances

   Potential: *Acquaintances* - 3

   Roll when you leverage someone you happen to know from here or
   there. Say who it is by name and how you know them. Say how they
   are helpful to know and what advantage or outcome you gain from
   knowing them. Do they help you out themselves? Does dropping their
   name get you in somewhere? GM sets a difficulty after hearing the
   outcome.

   *Hit* The player narrates the success

   *Bust* You gain the advantage or outcome but the acquaintance
   expects a favor, is displeased, or there is some other unintended
   consequence

   *Miss* You don't get the outcome you were hoping for. Choose 1
   - The acquaintance expects a favor
   - The acquaintance actively works against you
   - The acquaintance puts you at a disadvantage

** Face Death

   Potential: *Face Death*-4
   Difficulty: 4

   *Hit* You are incapacitated until you've healed an injury. Roll as per
   *long rest recovery* but without the requirement to eat and drink---you are
   unable to in a coma---and only once a day. If you don't heal an
   injury within 6 days you die.

   *Bust* You are incapacitated and must heal an injury fast. Roll as
   per *long rest recovery* as above. If you don't heal an injury you
   die.

   *Miss* You die

** Perception

   Potential: *Perception* - 2

   Hitchcock's Bomb, the players should be let in on it even if the
   characters are not. This roll should be about figuring out how much
   the PCs notice.

   GM honestly summarizes all the things available from the characters
   fictional position.

   *Hit* notice at least 3, at most all but 1

   *Bust* notice at least 1 at most all but 3

   *Miss* <something other than "whelp nope">

** Gossip

   Potential: Lower of *Perception*, *Acquaintances*

   Roll when you do something that relies on a plausible rumor's
   veracity that you heard through gossip. Players can invent these on
   the fly.

   *Hit* the rumor is true

   *bust* the rumor is true but it's just the tip of the iceberg choose one
   1. you're in over your head
   2. you've tipped your hand and the wrong people now know you were gossiping
   3. you've tipped your sources hand and they are displeased with you

   *miss* the rumor was false or misleading

** Fight

   Potential: Lower of 4 and *fight*-4 when fighting unarmed and the
   lower of 6 and *fight*-4 when fighting with improvised weapons
   like sticks, stones, or other tools not intended as weapons.

   When you fight toe to toe in melee (close) range roll with a
   difficulty of your opponent's *defense*.

   When you fight with a *weapon* that weapon's properties replace
   *fight's* properties.

   *Hit* The target must *face damage* as rolled

   *Bust* The target's next roll is at *disadvantage*

   *Miss* Your next roll is at *disadvantage*

** Face Damage

   Potential: Infinity

   When you are hit by a weapon, fall from a great height, or
   otherwise *face damage* roll with a difficulty of the damage faced.

   *Hit* GM chooses one as appropriate
   - suffer 2 strain for unarmed or improvised weapon
   - suffer 3 strain for a one handed weapon
   - suffer 5 strain for a two handed weapon
   - potentially more strain based on the circumstances. How high a
     fall was, how sharp the rocks are etc.

   *Miss* GM chooses one as appropriate
   - suffer 8 strain for an unarmed attack
   - suffer 10 strain for an improvised weapon
   - suffer 1 injury if hit by a one handed weapon
   - suffer 2 injuries if hit by a two handed weapon
   - potentially more injuries based on the circumstances. How high a
     fall was, how sharp the rocks are etc.

** Quick Draw

   Potential: *Anticipation*

   Roll when you *quick draw* a weapon.

   *Hit* You draw quickly. Immediately make another move.

   *bust* You draw relatively quickly, Immediately make another move
   with *disadvantage*.

   *Miss* You draw the weapon, but not very quickly. Others have an
   opportunity to make a move
* Appendix B: Special Talents
** Coin

   Potential: Higher of *perception* and *anticipation*

   Coin is not earned with experience but is worked for, traded for,
   found, stolen and so on. When you earn substantial *coin* increase
   the die size. PCs can't carry more than d12 coin on them.

   Roll when you spend *coin* to buy supplies or gear. The GM will
   come up with a difficulty representing the price based on rarity
   and cost to produce.

   *Hit* you can easily afford it

   *bust* You can afford it at some cost. Either don't buy it or
   reduce your coin die by one rank.

   *miss* You can afford it only at great cost (or not at all). Either
   don't buy it or reduce your coin by 3 ranks.

   Coin can be reduced to d0 (but not below)

** Supplies

   Supply dice are not bought with experience, they are bought with
   coin.

   Potential: Higher of *perception* and *anticipation*

   During a rest roll with a difficulty of your *strain* for each
   supply (meals, ammunition, etc.) you've used during this
   rest or at all since your last rest.

   *Hit* There are plenty more

   On a *bust* There are 5 more and on a *miss* there are 2
   more. Track these individually without rolling *supplies*

* Appendix C: Gear
** Thieves tools

   Potential: the quality of the tools

   | Potential | Tool Quality                |
   |-----------+-----------------------------+
   |         2 | Improvised                  |
   |         4 | Poor                        |
   |         6 | Average                     |
   |         8 | High                        |
   |        10 | Specialized or Expert Maker |
   |        12 | Advanced or Magic           |
   |        20 | Divine or Made by a God     |

   With enough persistence you can get past any lock. The only
   question is how much time will it take and how much attention will
   you draw. When you try to get past a lock roll any die up to
   *thieves tools*.

   Difficulty: the quality of the lock

   | Difficulty | Lock Quality                | Time on Hit | Time on Bust | Time on Miss |
   |------------+-----------------------------+-------------+--------------+--------------|
   |          2 | Poor                        | Seconds     | 1 Minute     | 5 Minutes    |
   |          3 | Average                     | Seconds     | 2 Minutes    | 1 Hour       |
   |          4 | High                        | Minutes     | 1 Hour       | 3 Hours      |
   |          5 | Specialized or Expert Maker | 1 Hour      | 3 Hours      | 10 Hours     |
   |          6 | Advanced or Magic           | 2 Hours     | 6 Hours      | 2 Days       |
   |         10 | Divine or Made by a God     | 5 Hours     | 2 Days       | 1 Week       |

** Camping Kit

   You've got everything you need to make camp. Gain advantage on
   *short rest* recovery rolls.

** Armor

   When you get armor, do all the character sheet calculations for
   when you wear it so that you don't have to figure it all out during
   a scene.

** Leather

   Armor Rating: 4 - number of injuries

** Chain Mail

   Armor Rating: 5

   *Fight* at *disadvantage*

** Plate

   Armor Rating: 6

   *Fight* at *disadvantage*, opponents fight at *advantage*

** Shield

   Armor Rating: +1, cannot use weapons two handed.

** Weapons
*** Spear

    Reach, Flexible, Ranged 40

*** Hand Axe

    Melee, Sunder

*** Battle Axe

    Melee, Two Handed, Sunder

*** Sword

    Melee, Finesse

*** Long Sword

    Melee, Two Handed, Finesse

*** Bow

    Ranged 120



