* Quill Core

  These are the core rules that don't require a roll and that talents
  may depend on or affect.

** Rest

   There are *short rests* and *long rests*. Each require you to eat
   and drink. Short rests take about an hour. Long rests take at least
   8 hours.

** Injury and Death

   For every *injury* you suffer, mark one of the unmarked
   *injuries*. When all *injuries* are marked you die.

** Recovery

   After a *long rest* if you might recover an *injury*. Roll xd6
   where x is your number of *injuries*. If the highest die is 1-4
   recover one *injury*

   To recover from all your *injuries*, when you start to rest roll xd6
   where x is the number of *injuries* you have taken. Rest that many
   consecutive days to recover all your *injuries*. If someone is
   tending to you roll one fewer dice.


*** Consider

    - stress pushing and resisting
    - specific injuries with drawbacks
    - Travel
    - Encumbrance

* Talents

  It's a tabletop role playing game so once the group has read this
  through, followed the instructions, and made some characters (PCs),
  the game master (GM) will describe the situation and the players
  will say what they do and the GM will say "okay" or "make a talent
  check" (or "wait, let's clarify the fiction"). And back and forth
  like that.

  Quill PCs have *talents* representing the difficult and powerful
  things they can do that might fail. PCs improve at *Talents* by
  earning and spending *experience* on their talents. Things like
  fighting with a particular weapon, perception, intimidation, casting
  wizard, cleric, or other spells, sneak attacks, and even keeping
  animal companions are all *talents*. How capable a PC is at each
  *talent* is represented by a die size. They all start at d4 and can
  progress with *experience* through the other die sizes (d6, d8, d10,
  d12 and d20).

** Talent Checks

   When a PC does something that is a *talent*, like fighting with a
   weapon, intimidating someone, or casting a spell, roll a check. The
   *talent* specifies a *potential* based on your character sheet and
   the GM determines a *difficulty* based on the fictional situation.
   The player rolls their die for that *talent*. If they roll under
   the *difficulty*, that's a *miss*. If they roll over the
   *potential* that's a *bust* (it can be both). Otherwise it's a
   *hit*

   The outcomes of talent checks, especially the consequences for
   *misses* and *busts*, are what drive the game forward.

   *Hit*: the player narrates their success

   *Miss*: the GM narrates the complication, setback, or obstacle that
   the failure causes. If the talent doesn't specify anything, invent
   something relevant to the situation.

   *Bust*: the GM narrates what the talent specifies or narrates a
   partial, incomplete, or fatally flawed success and possibly also a
   complication, setback, or obstacle it causes. A *bust* shouldn't be
   as bad as a *miss*.

   The following shows roughly what each *talent* die level represents
   along with rough guidance for the GM to determine a check's
   *difficulty*

   | Talent Die | Level of Experience | Challenging | Impossible |
   |------------+---------------------+-------------+------------|
   | d4         | No training         |           2 |          5 |
   | d6         | Some training       |           3 |          7 |
   | d8         | Well trained        |           4 |          9 |
   | d10        | Expert              |           5 |         11 |
   | d12        | Expert Specialist   |           6 |         13 |
   | d20        | Godlike             |          10 |         21 |
* Talent properties

  There are some properties that are named here, and then simly
  referenced in their talent description. Things like range for
  weapons, verbal and somatic components for spells etc.

* Creating Characters

  Distribute this array of dice [d10, d8, d8, d6, d6, d6] to any
  *talents* you'd like to start with. All PCs can use any *talent* at
  d4

  Take as much gear as you want but check with your GM and other
  players first to make sure everyone is happy with it.

  Complete the calculations on your chatacter sheet.

