+++
title = "Quill"
version = "0.3.0-draft"
subtitle = ""
date = 2020-05-22T07:44:45-05:00
draft = true
categories = [
  "Zines",
]
+++

I'm assuming that you are familiar with role playing games. Quill
won't explain much of what is common to most of them so If you are new
to roleplaying, I hope a little internet research will clear anything
up. If not please let me know either on Twitter (@jessebmiller),
through email <jesse@jessebmiller.com> or on the [Porcupine Studio
chat](chat.porcupine.studio) (Discord at the time of this writing).

Quill was influenced by a bunch of great prior work.

*Dungeons & Dragons* by Wizards of the Coast

*Blades in the Dark* by John Harper

*Apocalypse World* by Meguey and D. Vincent Baker

Thank you for the path you blazed!

The object of Quill is to *become powerful* by the *experience of
dangerous adventure* but you might not because the *danger is real*
and *you could fucking die*.

* Design Goals

  - *It should be opinionated*. Strong choices for a focused audience
  - *Minimal quick math* Move calculations out of the flow of play and
    into character creation or session downtime
  - *Simple rule set* Minimal cross references and look ups,
    especially during the flow of play.
  - *Large design space* Support hacking and custom content.
  - *Efficient expert execution* Once a group masters the system, they
    all should easily maintain continuity and agreement about the
    whole of the fiction
  - *Enjoyable* Even groups that haven't yet mastered the system
    should none the less enjoy their time playing
  - *Rules that drive the game* Rules should always drive the goals of
    the game, and may take players out of their characters to do so.
  - *Zine friendly* It should be a small core ruleset that fits in a
    small book. Expansions should fit in similarly small books.

* Safety

  At the beginning of every session, mention the X card, and ask if
  anyone has any lines or veils they want to have in place for the
  session. Something freeing and great happens when the game is safe
  and everyone knows what lines not to cross and trusts that everyone
  can speak up if something makes them uncomfortable trusting that the
  group will change it without judgment. Everyone can go a little
  deeper safe in the knowledge that if they go too far someone will
  speak up and everyone will step back and change it.

* Judgment calls

  When you play, you’ll make several key judgment calls. Everyone
  contributes, but either the players or the GM gets final say for
  each:

  - Which actions are reasonable as a solution to a problem? /Can this
    person be intimidated? Must we get out the thieves tools and/
    /tinker with this old rusty lock, or could it also be quietly
    finessed?/ The players have final say.
  - How dangerous and how effective is a given action in this
    circumstance? /How risky is this? Can this person be swayed very
    little or a whole lot?/ The GM has final say.
  - Which consequences are inflicted to manifest the dangers in a
    given circumstance? /Does this fall from the roof break your leg?
    Do the constables merely become suspicious or do they already have/
    /you trapped?/ The GM has final say.
  - Does this situation call for a dice roll, and which one? /Is your
    character in position to make an action roll or must they first/
    /make a resistance roll to gain initiative?/ The GM has final say.

* The Basics

  These are the core rules that don't require a roll and that talents
  may depend on or affect.

** Rest

   There are *short rests* and *long rests*. Each require you to eat
   and drink. Short rests take about an hour. Long rests take at least
   8 hours.

** Injury and Death

   For every *injury* you suffer, mark one of the unmarked
   *injuries*. When all *injuries* are marked *face death*.

** Recovery

   After a *short rest* recover 1d6 *strain*

   After a *long rest* recover all *strain*.

   After a *long rest* if you have an *injury* to recover roll xd6
   where x is your number of *injuries*. If the highest die is 1-4
   recover one *injury*

   To recover from all your *injuries*, when you start to rest roll xd6
   where x is the number of *injuries* you have taken. Rest that many
   consecutive days to recover all your *injuries*. If someone is
   tending to you roll one fewer dice.

** Strain

   When *strain* is greater than 12 suffer 1d4 injuries and pass out
   for 20 minutes or until attended to for at least 1 minute. Upon
   waking you must immediately take a short rest (which means eat and
   drink) or pass out again.

*** Pushing

    You can push yourself on any check and take as many of the
    following as you want as many times as you want but declare it all
    and take the *strain* before you roll the check.

    - take 1d6 *strain* and gain advantage or lose disadvantage
      (take this twice to go from disadvantage to advantage)
    - take 1d6 *strain* and roll 1 die level higher
    - take 1d8 *strain* and roll 2 die levels higher
    - take 1d10 *strain* and roll 3 die levels higher
    - take 1d4 *strain* and reduce the difficulty by 1
    - take 1d4 *strain* and increase your effective *potential* by 1
    - take 1d12 *strain* to get an automatic *hit*
    - take 1d10 *strain* to get an automatic *bust*

*** Resisting

    After you roll you can resist the consequence of a *bust* or a
    *miss* by paying *strain*. Narrate how you are avoiding it then roll
    to see how much *strain* you take to do it.

    take 1dx *strain* where x is the same die you rolled for a *miss*
    and one level lower for a *bust* to a minimum of 4.

** Flashbacks

   The rules don’t distinguish between actions performed in the
   present moment and those performed in the past. When an operation
   is underway, you can invoke a flashback to roll for an action in
   the past that impacts your current situation. Maybe you convinced
   the district Watch sergeant to cancel the patrol tonight, so you
   make a Sway roll to see how that went.

   The GM sets a *strain* cost when you activate a flashback action.

   - 0 Strain: An ordinary action for which you had easy
     opportunity. Consorting with a friend to agree to arrive at the
     dice game ahead of time, to suddenly spring out as a surprise
     ally.
   - 1 Strain: A complex action or unlikely opportunity. Finessing
     your pistols into a hiding spot near the card table so you could
     retrieve them after the pat-down at the front door.
   - 2 (or more) Strain: An elaborate action that involved special
     opportunities or contingencies. Having already Studied the
     history of the property and learned of a ghost that is known to
     haunt its ancient canal dock—a ghost that can be compelled to
     reveal the location of the hidden vault.

   After the strain cost is paid, a flashback action is handled just
   like any other action. Sometimes it will entail an action roll,
   because there’s some danger or trouble involved. Sometimes a
   flashback will entail a fortune roll, because we just need to find
   out how well (or how much, or how long, etc.). Sometimes a
   flashback won’t call for a roll at all because you can just pay the
   strain and it’s accomplished.

   If a flashback involves a downtime activity, pay 1 coin or 1 rep
   for it, instead of strain.

   One of the best uses for a flashback is when the engagement roll
   goes badly. After the GM describes the trouble you’re in, you can
   call for a flashback to a special preparation you made, “just in
   case” something like this happened. This way, your “flashback
   planning” will be focused on the problems that _do _happen, not the
   problems that might happen.

*** Limits of flashbacks

    A flashback isn’t time travel. It can’t “undo” something that just
    occurred in the present moment. For instance, if an Inspector
    confronts you about recent thefts of occult artifacts when you’re
    at the Lady’s party, you can’t call for a flashback to assassinate
    the Inspector the night before. She’s here now, questioning
    you---that’s established in the fiction. You can call for a
    flashback to show that you intentionally tipped off the inspector
    so she would confront you at the party---so you could use that
    opportunity to impress the Lady with your aplomb and daring.

**** Flashback examples

     > “I want to have a flashback to earlier that night, where I sneak
     > into the stables and feed fireweed to all their goats so they’ll
     > go berserk and create a distraction for our infiltration.”
     >
     > “Ha! Nice. Okay, that’s seems a bit tricky, dealing with ornery
     > goats and all... 1 strain.”
     >
     > “Should I roll Prowl to sneak in and plant it?”
     >
     > “Nah. Their goat stable security amounts to a stable boy who is
     > usually asleep anyway. You can easily avoid their notice.”
     >
     > “So it just works?”
     >
     > “Eh... not so fast. When you want the distraction to hit, let’s
     > make a fortune roll to see how crazy the Fireweed Goat Maneuver
     > gets. Three dice.”

     ---

     > “The engagement roll is... a 2. Looks like a desperate situation
     > for you! Hmmm. Okay, so you’re inside the gang’s compound at the
     > docks, slipping up through the shadows next to some huge metal
     > storage tanks. But then all the electric lights come on. The big
     > metal warehouse door rolls open, and you hear a heavy wagon
     > coming in through the gate. Looks like they’re getting a delivery
     > right now, and a bunch of gang members are out to receive
     > it. They’re about to be on top of you. What do you do?”
     >
     > “Hang on, I want to have a flashback.”
     >
     > “Okay, for what?”
     >
     > “Uh. Something... helpful? Damn, I don’t know what that would
     > be. Anyone have ideas?”
     >
     > “Oh, what if you Consorted with your docker friends yesterday and
     > they blabbed about this delivery, so we rigged it with a bomb.”
     >
     > “Oh man, that’s hilarious. But kind of nuts. I guess 2 strain for
     > that?”
     >
     > “Sounds good. But let’s make that Consort roll and see if your
     > docker friends made any demands or complicated anything for
     > you. Then we need to find out how well this bomb works. Who was
     > in charge of that?”
     >
     > “I did it. I’ll roll Tinker to set the fuse just
     > right. Hopefully.”
* The Talents

  It's a tabletop role playing game so once the group has read this
  through, followed the instructions, and made some characters (PCs),
  the game master (GM) will describe the situation and the players
  will say what they do and the GM will say "okay" or "make a talent
  check" (or "wait, let's clarify the fiction"). And around and
  around.

  Quill PCs have *talents* representing the difficult and powerful
  things they can do that might fail. PCs improve at *Talents* by
  earning and spending *experience* on their talents. Things like
  fighting with a particular weapon, perception, intimidation, casting
  wizard, cleric, or other spells (see the Quill Magic zine), sneak
  attacks, and even keeping animal companions are all *talents*. How
  capable a PC is at each *talent* is represented by a die size. They
  all start at d4 and can progress with *experience* through the other
  die sizes (d6, d8, d10, d12 and d20).

** Talent Checks

   When a PC does something that is a *talent*, like fighting with a
   weapon, intimidating someone, or casting a spell, roll a check. The
   *talent* specifies a *potential* based on your character sheet and
   the GM determines a *difficulty* based on the fictional situation.
   The player rolls their die for that *talent*. If they roll under
   the *difficulty*, that's a *miss*. If they roll over the
   *potential* that's a *bust* (it can be both). Otherwise it's a
   *hit*. Many talents base *potential* on other talents or even the
   same talent itself. In these cases use the /die size/ you have in
   the talent for *potential*. For example, *Gossip* specifies "The
   lower of *Perception* and *Acquaintances*". Say your *Perception*
   was *d10* and your *Acquaintances* was *d6* your *potential* for
   *Gossip* would be *6* as it's the lower of 10 and 6.

   The outcomes of talent checks, especially the consequences for
   *misses* and *busts*, are what drive the game forward and unless
   otherwise stated use this as a guide.

   *Hit*: the player narrates their success

   *Miss*: the GM narrates the complication, setback, or obstacle that
   the failure causes. If the talent doesn't specify anything, invent
   something relevant to the situation.

   *Bust*: the GM narrates what the talent specifies or narrates a
   partial, incomplete, or fatally flawed success and possibly also a
   complication, setback, or obstacle it causes. A *bust* shouldn't be
   as bad as a *miss*.

   This table shows roughly what each *talent* die level represents
   along with rough guidance for the GM to determine a check's
   *difficulty*

   | Talent Die | Level of Experience | Challenging | Impossible |
   |------------+---------------------+-------------+------------|
   | d4         | No training         |           2 |          5 |
   | d6         | Some training       |           3 |          7 |
   | d8         | Well trained        |           4 |          9 |
   | d10        | Expert              |           5 |         11 |
   | d12        | Expert Specialist   |           6 |         13 |
   | d20        | Godlike             |          10 |         21 |

** Advantage and Disadvantage

   Some rules grant you *advantage* or give you *disadvantage*. When
   you have *advantage* roll 2 dice and take the better die. When you
   have *disadvantage* roll 2 and take the worse. A *hit* is better
   than *bust* is better than *miss*

** Talent properties

   There are some properties that are named here, and then simply
   referenced in their talent description. Things like range for
   weapons, verbal and somatic components for spells etc.

*** Melee

    Potential: *Fight* when used in melee range

*** Ranged X Y

    Potential: Lower of *Perception* and *Anticipation* when used
    outside beyond melee range up to X feet. Every Y feet beyond that
    the target gains 1 *defense*

*** Reach

    Potential: *Fight* when used in melee range or just outside of
    melee range.

    When you *fight* just beyond melee range with a *reach* weapon you
    can keep one opponent from entering melee range until they find an
    opportunity to close. When you *fight* with a *reach* weapon in melee
    range you are *disadvantaged*

    The opponent may move into melee range whenever you *miss*. If they
    do you must *quick draw* at *disadvantage* in order switch to a
    melee weapon.

    The opponent may move into melee range whenever you *bust*. If they
    do you must *quick draw* with *advantage* in order to switch to a
    melee weapon.

*** Sunder

    When you *fight* and *bust* reduce the target's armor by 1 in
    addition to any other effects.

*** Finesse

    For the purposes of determining *defense* when fighting with a
    *finesse* weapon treat your number of injuries as one fewer. This
    makes your base unarmored defense 4 with no injuries.

*** Flexible

    Can be used either one handed or two handed.

* Creating Characters

  Distribute 2d10, 3d8, and 4d6 to any *talents* you'd like to start
  with. Only one die level per talent. All PCs start with every
  *talent* at d4

  Take as much gear as you want but check with your GM and other
  players first to make sure everyone is happy with it.

  Complete the calculations on your chatacter sheet.

* Advancement

  When you *push yourself* and *miss* using a *talent* mark it for an
  Experience Point (*XP*). Once you've marked enough *XP* for a talent
  you may advance it to its next highest die by paying its cost in
  *XP* during a long rest. All PCs have a d4 in every *talent*.

  | Next Die | XP Cost |
  |----------+---------|
  | d6       |       1 |
  | d8       |       2 |
  | d10      |       3 |
  | d12      |       4 |
  | d20      |       8 |

* Appendix A: Talents
** Animal Companionship

   Potential: Lower of *perception* and *Animal Companionship*-4

   When you dedicate a few hours and work to form a bond of
   companionship with an animal, either set up a new 5 step
   companionship clock or make progress on an existing companionship
   clock by rolling

   Difficulty:

   | Difficulty | Animal                                                  |
   |------------+---------------------------------------------------------|
   |          2 | Domestic animals (Dogs, Cats, Ravens, Horses)           |
   |          4 | Wild domestic Counterparts (Wolves, Big Cats, Raptors)  |
   |          6 | Other wild animals (Elephants, Reptiles, Bears, Jackal) |
   |          8 | Dire Animals                                            |
   |         10 | Beasts                                                  |
   |         12 | Monsters                                                |

   *Hit* Mark two ticks on the clock

   *Bust* Mark one tick on the clock

   *Miss* Remove one tick on the clock

** Anticipation

   Potential: *Anticipation*-4

   Roll when you think you could have *anticipated* something. Say how
   you anticipated it and how you are prepared.

** Acquaintances

   Potential: *Acquaintances*-3

   Roll when you leverage someone you happen to know from here or
   there. Say who it is by name and how you know them. Say how they
   are helpful to know and what advantage or outcome you gain from
   knowing them. Do they help you out themselves? Does dropping their
   name get you in somewhere? GM sets a difficulty after hearing the
   outcome.

   *Hit* The player narrates the success

   *Bust* You gain the advantage or outcome but the acquaintance
   expects a favor, is displeased, or there is some other unintended
   consequence

   *Miss* You don't get the outcome you were hoping for. Choose 1
   - The acquaintance expects a favor
   - The acquaintance actively works against you
   - The acquaintance puts you at a disadvantage

** Face Damage

   Potential: Infinity

   Difficulty: The damage faced

   Roll when you are hit by a weapon, fall from a great height, or
   otherwise *face damage*.

   *Hit* GM chooses one as appropriate
   1. suffer 2 strain for unarmed or improvised weapon
   2. suffer 3 strain for a one handed weapon
   3. suffer 5 strain for a two handed weapon
   4. potentially more strain based on the circumstances. How high a
      fall was, how sharp the rocks are etc.

   *Miss* GM chooses one as appropriate
   1. suffer 8 strain for an unarmed attack
   2. suffer 10 strain for an improvised weapon
   3. suffer 1 injury if hit by a one handed weapon
   4. suffer 2 injuries if hit by a two handed weapon
   5. potentially more injuries based on the circumstances. How high a
      fall was, how sharp the rocks are etc.

** Face Death

   Potential: *Face Death*-4
   Difficulty: 4

   *Hit* You are incapacitated until you've healed an injury. Roll as per
   *long rest recovery* but without the requirement to eat and drink---you are
   unable to in a coma---and only once a day. If you don't heal an
   injury within 6 days you die.

   *Bust* You are incapacitated and must heal an injury fast. Roll as
   per *long rest recovery* as above. If you don't heal an injury you
   die.

   *Miss* You die

** Fight

   Potential: Lower of 4 and *fight*-4 when fighting unarmed and the
   lower of 6 and *fight*-4 when fighting with improvised weapons
   like sticks, stones, or other tools not intended as weapons.

   When you *fight* toe to toe in melee (close) range roll with a
   difficulty of your opponent's *defense*.

   When you *fight* with a *weapon* that weapon's properties replace
   *fight's* properties.

   *Hit* The target must *face damage* as rolled

   *Bust* The target's next roll is at *disadvantage*

   *Miss* Your next roll is at *disadvantage*

** Gossip

   Potential: Lower of *Perception*, *Acquaintances*

   Roll when you do something that relies on a plausible rumor's
   veracity that you heard through gossip. Players can invent these on
   the fly.

   *Hit* the rumor is true

   *Bust* the rumor is true but it's just the tip of the iceberg choose one
   1. you're in over your head
   2. you've tipped your hand and the wrong people now know you were gossiping
   3. you've tipped your sources hand and they are displeased with you

   *Miss* the rumor was false or misleading

** Intimidation

   Potential: *Intimidation*-5
   - +1 if you have a credible reputation for violence or retaliation
     and they are aware of it
   - +1 if you brandish a deadly weapon
   - +1 if they are not wearing armor
   - +1 if they have a d4 in *fight*
   - +1 if they have a d12 in *fight*

   Roll when you threaten retaliation in order to get what you want.

   *Hit* You get what you want

   *Bust* You get what you want but whoever you intimidated holds 2
   against you until the end of the scene. They may spend one hold to
   give you disadvantage or to gain advantage against you for one
   check.

   *Miss* You don't get what you want and whoever you intimidated
   holds 3 and may spend them as above.

** Perception

   Potential: *Perception* - 2

   Hitchcock's Bomb, the players should be let in on it even if the
   characters are not. This roll should be about figuring out how much
   the PCs notice.

   GM honestly summarizes all the things available from the characters
   fictional position.

   *Hit* notice at least 3, at most all but 1

   *Bust* notice at least 1 at most all but 3

   *Miss* <something other than "whelp nope">

** Quick Draw

   Potential: *Anticipation*

   Roll when you *quick draw* a weapon.

   *Hit* You draw quickly. Immediately make another move.

   *bust* You draw relatively quickly, Immediately make another move
   with *disadvantage*.

   *Miss* You draw the weapon, but not very quickly. Others have an
   opportunity to make a move

** Sneak Attack

   Potential:
   - *Quic Draw* when you use suddenness of attack to catch them off
     guard
   - *Anticipation* when you lay in wait
   - *Stealth* when you sneak up on them
   - *Perception* when they are fully engaged on something else (like
     fighting someone else, or taking aim at someone else, or
     equivalent attention otherwise

   Difficulty: Their defense as though they have 3 injuries

   When you attack someone who is unaware of your intention roll

   *Hit* as though they were hit by the weapon you wield. They face
   damage as though it were one level more severe

* Appendix B: Special Talents
** Coin

   Potential: Higher of *perception* and *anticipation*

   Coin is not earned with experience but is worked for, traded for,
   found, stolen and so on. When you earn substantial *coin* increase
   the die size. PCs can't carry more than d12 coin on them.

   Roll when you spend *coin* to buy supplies or gear. The GM will
   come up with a difficulty representing the price based on rarity
   and cost to produce.

   *Hit* you can easily afford it

   *bust* You can afford it at some cost. Either don't buy it or
   reduce your coin die by one rank.

   *miss* You can afford it only at great cost (or not at all). Either
   don't buy it or reduce your coin by 3 ranks.

   Coin can be reduced to d0 (but not below)

** Supplies

   Supply dice are not bought with experience, they are bought with
   coin.

   Potential: Higher of *perception* and *anticipation*

   Difficulty: *Strain*

   After each rest roll for each supply (meals, ammunition, etc.) if
   you used it since your previous rest.

   *Hit* There are plenty more

   On a *bust* There are 5 more and on a *miss* there are 2
   more. Track these individually without rolling *supplies*

* Appendix C: Gear
** Thieves tools

   Potential: the quality of the tools

   | Potential | Tool Quality                |
   |-----------+-----------------------------+
   |         2 | Improvised                  |
   |         4 | Poor                        |
   |         6 | Average                     |
   |         8 | High                        |
   |        10 | Specialized or Expert Maker |
   |        12 | Advanced or Magic           |
   |        20 | Divine or Made by a God     |

   With enough persistence you can get past any lock. The only
   question is how much time will it take and how much attention will
   you draw. When you try to get past a lock roll any die up to
   *thieves tools*.

   Difficulty: the quality of the lock

   | Difficulty | Lock Quality                | Time on Hit | Time on Bust | Time on Miss |
   |------------+-----------------------------+-------------+--------------+--------------|
   |          2 | Poor                        | Seconds     | 1 Minute     | 5 Minutes    |
   |          3 | Average                     | Seconds     | 2 Minutes    | 1 Hour       |
   |          4 | High                        | Minutes     | 1 Hour       | 3 Hours      |
   |          5 | Specialized or Expert Maker | 1 Hour      | 3 Hours      | 10 Hours     |
   |          6 | Advanced or Magic           | 2 Hours     | 6 Hours      | 2 Days       |
   |         10 | Divine or Made by a God     | 5 Hours     | 2 Days       | 1 Week       |

** Camping Kit

   You've got everything you need to make camp. Gain advantage on
   *short rest* recovery rolls.

** Armor

   When you get armor, do all the character sheet calculations for
   when you wear it so that you don't have to figure it all out during
   a scene.

** Leather

   Armor Rating: 4 - number of injuries

** Chain Mail

   Armor Rating: 5

   *Fight* at *disadvantage*

** Plate

   Armor Rating: 6

   *Fight* at *disadvantage*, opponents *fight* at *advantage*

** Shield

   Armor Rating: +1, cannot use weapons two handed.

** Weapons
*** Spear

    Reach, Flexible, Ranged 40

*** Hand Axe

    Melee, Sunder

*** Battle Axe

    Melee, Two Handed, Sunder

*** Sword

    Melee, Finesse

*** Long Sword

    Melee, Two Handed, Finesse

*** Bow

    Ranged 120

* License

This work is licensed under a Creative Commons Attribution 4.0
International License (http://creativecommons.org/licenses/by/4.0/).

This work is based on *Blades in the Dark* (found at
http://www.bladesinthedark.com/), product of One Seven Design,
developed and authored by John Harper, and licensed for our use under
the Creative Commons Attribution 3.0 Unported license
(http://creativecommons.org/licenses/by/3.0/).
