+++
title = "R.A.C.K."
subtitle = ""
date = 2020-06-07T12:05:35-05:00
draft = true
categories = [
  "Zines",
]
+++

* The conversation

  R.A.C.K. Is a proper live action role playing game, and as such is a
  conversation (sometimes non-verbal) in which the players construct a
  unanimously agreed upon fictional reality together through up front
  consent between equals to a procedure and set of rules that supplant
  our normal interests in order to experience situations we normally
  wouldn't.

* Safety

  - Safe words (No means no unless explicitly discussed)
    - Discuss the risk of forgetting the safe word
    - Discuss the risk of getting into a habit of not explicitly
      discussing this before every session
  - Discuss risks
  - Limits
  - Aftercare

  You must talk about your limits, you may talk about your desires.

* Dominance and submission

  In which one character gives up--or has taken away--power, autonomy,
  and agency by another character.

** Characters
*** Dominant
*** Submissive

** Promiscuity humiliation

   In which one character in a committed relationship with another
   humiliates them through promiscuity with an intimidating third
   character of a form the former is not capable of performing.

*** Characters
**** The Humiliated
**** The Promiscuous
**** The Intimidating

** Maturity discrepancy

   In which one immature character is incapable of caring for
   themselves and relies on the care of another more mature character

* Sensations

  In which one player requests sensations and another provides them.

  These are maybe not role playing games because there is no shared
  fiction.

** Pain
** Pleasure
** Sensory Deprivation

** Situational

   The sensations of different situations. Many of these are D/s
   adjacent but do not come with the exchange of power of D/s play.

   - being tied up
   - being above or below someone
   - being exposed
   - being inspected
   - being dressed a certain way

** Emotional

   - Praise
   - Danger from knives
   - Humiliation


* Taboo

  In which characters, in a shared fiction, break taboos that players
  would never break.

** Public
** Familial
** Maturity

* License

This work is licensed under a Creative Commons Attribution 4.0
International License (http://creativecommons.org/licenses/by/4.0/).
