+++
title = "The Beast in the Garden"
subtitle = ""
date = 2020-05-30T07:36:23-05:00
draft = true
categories = [
  "Playtest Document",
]
+++

The object of the game is to weaken the leviathan but you might not
because it is more powerful, more brutal, and more organized than you

The object of the game is to see yourself liberated but you might not
because the system is more powerful, more brutal, and more organized
than you

The object of the game is to see your communities liberated but you
might not because the system is more powerful, more brutal, and more
organized than you

The object of the game is to apply your power and privilege to
liberation and justice but you might not because the system is more
powerful, more brutal, and more organized than you

The Beast in the Garden is about power, brutality, and organization

The Beast in the Garden is about liberation and justice

The Beast in the Garden is about a social justice cold war

The Beast in the Garden is about institutions and movements

Brutality is like a strong wind to flame. When the flame is small it
extinguishes but when large it incites escilation. People however are
not candles. When our furver is extinguished through violent
escilation we remember, we prepare, and we organize resistence. We
form movements to fight it. We defend each other.

* Notes on a possibility

  * It's like microscope for the entire campaign narrative
  * We decide starting conditions, and an ending tragic situation with
    one remaining question (like Dialect)
  * There is a classic GM but also lots of passing of specific
    responsibilities (like Microscope)
  * Scenes are framed by asking questions
  * Epic theatre techniques to break players out and focus them on
    what their story means
  * Mythic GM style tools for bringing in scenes, characters, etc.
  * Scenes drill down and establish facts, flesh out the narrative,
    with events, motivations, communications etc.
  * The game is played in non linear time, scenes can happen anywhere
    in the timeline (or even at the same time from a different
    perspective)
  * Trends can "overlay" on each other? one throughline in multiple eras?
    * Like Cloud Nine

* The Game Structure

  Dogs in the Vineyard conflicts and fallout
  + escalation dice for institutional support
  + institution specific fallout
  + dice and escalation options for being organized, brutal
  + Tacit coordination deescalation Schelling games

  Narration occurs in one continuous plot that jumps between eras yet
  is the same continuous plot. The scenery, specifics, and dates
  change, but it's the same story.

  The story starts on
  * April 21, 1861: The Confederate attack and the struggle for
    emancipation
  * May 17, 1954: The unanimous decision and the struggle for the
    civil rights bill
  * November 8, 2016: The 45th election and the struggle for the
    mattering of Black lives

  Or maybe the leviathan story is more broad than that. The leviathan
  is colonists and the sovereignty they established.
  - Its arrival in America and the beginning of the transatlantic
    slave trade.
  - The civil war against its stranglehold on the south
  - Today with folks keeping it alive and trying to nurture it back to
    health after the damage done to it by the civil rights movement. I
    don't want to let white people today off the hook for wielding and
    wanting more of the power it gave and could give us.

  The beast is Hobbs's leviathan and the garden is "the new world"

  Players play characters whose lives, like in cloud nine, spanned
  from the 15th century to today. The game starts in medias res in the
  near future during the final conflict in which the characters
  struggles will end possibly tragically, possibly by defeating the
  leviathan. It flashes back to the characters throughout their lives in
  the slavery era 15th-19th centuries, the abolition Civil War era,
  and the civil rights era.

  Structure the whole game like a future passover seder in which we
  tell the story of our struggle for freedom from oppression in
  America.

  - Structure everything with ritual like song, recitation in unison,
    etc.
  - play to answer questions like
    - How did you contribute to and survive X, What did it cost?
      - the journey across the Atlantic?
      - the uprising a, b, and c?
      - The underground railroad?
        - Did you escape? Did you help anyone escape?
        - What did you lose? What did you have to do?
      - the Civil War battles a, b, and c?
      - protests x, y, z

  Keep track of wealth (and what that wealth might have grown to
  today) that had to be given up when answering the questions.

* Institutions

  - Government (Policy, Courts, Enforcement) claims a monopoly on the
    legitimate use of violence. Is generally granted that monopoly.
  - Media writes public opinion which grants government violence
    legitimacy, as long as it falls within accepted moral bounds.
  - Religious have a monopoly on the definition of accepted moral
    bounds.
  - White Nationalist attempt to reverse the work of activists and
    increase white power through the oppression of all other power.

  Institutions have moves and 

* Player Characters

  - Activist attempt to disrupt the institutional status-quo.
  - Regular Folks just trying to live their lives, be good people, and
    find prosperity.

  The PCs and their narrative runs simultaneously in all three
  eras. They are not flashbacks, they are the same people in the same
  situation.

  the PCs are not villains, but they also aren't heroes. They don't
  have a responsibility to anyone but themselves and whoever else they
  want. They are allowed to decide to be heroes but the game does not
  expect them to be.

* Conflicts


* Morgue
- Institutions
  - Government (Policy, Courts, Enforcement)
  - Media
  - Religious
  - Activist
- Brutality and escalation strategies
  - Can you escalate farther than me? is that obvious?
  - How organized are you, how many people can you bring to bear in
    different arenas? When escalation gets here, you have more power
  - Each institution brings it's own fallout (and threat of fallout)
    into the conflict when their dice are brought into the conflict
    - Institutions each get their own fallout lists
  - Set up situations like in the strategy of conflict
- bargaining, communication, and limited war. This is what's happening
  right now in America
  - divergence of interest
  - limited communication
  - inhibited negotiation
  - tacit coordination common interests
    - in places throughout the game, ask "what are the common
      interests? is there explicit coordination?
    - Explicit coordination is handled with dogs in the vineyard style
      conflicts
    - Tacit coordination is handled with Schelling games and offers an
      exit from the conflict other than Giving

- NASA in the 60s and spaceX in 2020

* Influences
- Black Lives Matter
- Southern Poverty Law Center
- Dog Eat Dog by Liam Liwanag Burke
- Ironsworn by Shawn Tomkins
- Dogs in the Vineyard by D. Vincent Baker
- Cloud Nine Caryl Churchill
- The Strategy of Conflict by Thomas C. Schelling
- The Beast by The Fugees

* Darling Dogs in the Vineyard

  Demonic Influence -> Systems of Oppression

** Dogs? Towns?

   Are the characters villains? if so they are playing the cops, KKK,
   and slaveholders

   Are the characters the oppressed? if so maybe this isn't dogs in
   the vineyard? Is dogs a darling?

   Escalation and fallout are the things I want from it, are those
   essential? extricable from the PC as Villain thing? (sounds like I
   don't want the PCs to be villains)

   Is this PbtA instead? no

   I think it's the fallout I want. something that builds up over time
   until you can't breathe. It's what should happen to a villain to
   incite redemption, but it's also been happening to black people in
   America as long as it's been here so...

   It's escalation too though and especially being incited into
   escalation...

   Can I do this with other-kind dice, arenas, and fallout? let's see

* Other-kind coins

  *This whole other-kind dice and coin thing could all be darlings.*

  *it might be worth trying this with pure Dogs dice and bidding first*

  State your goal, can be as broad or as detailed as the narrative
  demands. The GM and others state risks, maybe there are moves that
  help guide the statement of goals and risks, the allotment of coins,
  etc.

  Ask questions about the characters situation and their *motivations*
  when rolling. They get bonus coins to their pool for relevant
  motivation. Maybe this can just be stats like dogs first. small
  steps.

  At the start of a conflict, we both flip a bunch of coins. but
  instead of seeing, blocking, raising etc. we go back and forth like
  in other-kind dice. Go back and forth stating actions the other
  can't ignore, adding risks and assigning coins to achieve actions,
  avoid risks, etc. The actor gets 3 pennies to flip for risk added.

  The person taking the action assigns up to 2 coins to the outcome
  and up to 2 coins to any risk. Then the opponent must match or
  exceed them on the outcome or Give. and may outspend them on the
  risks or accept the risk occurring.

  if they do it for the outcome with fewer coins, they reverse the
  blow, and get to keep those coins for later in the conflict, they
  block if they do it with an equal number of coins, and they take the
  blow if they do it with more coins, those coins go into the fallout
  pool. if they match the value on the risks they don't happen, no
  fallout from there, but no reversing the blow either.

  When the GM adds a risk the PC flips and adds 2? pennies? to their
  pool.

* Progress

  Like long term project progress

* Cloud Nine Shit

  How do we determine when we are in what era? explicit scene setting?
  one era per scene? can a scene switch eras? if so when? just
  whenever someone wants it to they say that it does? Can one
  character be in one era than the rest of the scene? why not let's
  try it?

  A character who dies, does so in all three eras like everything else

  Maybe there is a specific series of scenes or prompts that make up
  the game, or questions like for the queen, or conflicts.

  Maybe there is a specific series of things that the institutions do
  and we play within that framework. Maybe they are somewhat
  randomized, maybe our actions can effect them, but maybe that's
  supper hard.

  This could be a "The Beast" deck with prompts, events, etc. that
  becomes a backdrop for play. Choosing what goes into the deck
  becomes a way to craft the world.

  Scenes -> Goals -> Conflicts -> Fallout

  Institutions get stronger and weaker in each arena

  Characters get stronger and weaker in arenas and institutions

  When institutions get involved in the conflict each character rolls
  the lower of their dice (in both number and rank) in the institution
  and the institution's dice in the arena. If it escalates to a new
  arena do the same for the new arena.

  Example
  - The police have 6d10 in all physical arenas
  - The mayor has 6d12 in the police
  - White privilege gives 2d10 in the police
  - Black characters get 1d6 in the police
  - When the police get involved in a physical conflict, white
    characters roll 2d10, black characters roll 1d6 and the mayor
    rolls 6d10

  Conflicts:
  - When a conflict starts, or whenever someone tries to change to a
    new arena. you gather any dice and see the oppositions pile
    ask
    - What are each characters interests?
    - if the characters are not communicating about the new arena play
      a Schelling game.
      - The game is for each to state the same outcome acceptable to
        both parties in the new arena, given that the conflict will go
        to the highest escalation level of anyone's stated outcome.
      - If they coordinate that's the outcome, if not do the conflict
        - Interesting question here about multiparty coordination. how
          many parties must coordinate? Perhaps the uncoordinated lose
          dice for the conflict
      - If there are interests that are not addressed by the outcome
        anyone can restart the conflict
    - Roll dice, take actions the other can't ignore etc. per dogs in
      the vineyard

* My Darlings
** NPCs

   NPCs are archetypes, they have "playbooks" that the GM can use to
   lazily evaluate them, tables and prompts and things. They have
   details for each era, the 45th, the war, and the movement.

*** Bad Cop

    Explicitly racist. Coordinated and affiliated with white
    nationalists

*** Good Cop

    but not good enough to organize and arrest the bad cops

*** City Politician
*** Reporter
*** Religious Leader
*** White Nationalist Organizer
*** Activist Organizer
*** Citizen
*** Arenas of conflict and motivation

    Fictional position motivational arenas and characters orientation to
    them. What holds weight to characters? Physical does by default,
    what about different moralities? Religions? Love? Sex? Money? Peer
    pressure?  Etc...

    This is used for both advancement, progress along tracks, and can be
    used to incite a character to escilate conflicts.

    All characters get ratings in the base arenas

    Base Arenas
    * Social: love, friendship, community, family
    * Physical: pleasure, pain, injury, restraint, imprisonment
    * Emotional: curiosity, fear, anger, sadness, joy, disgust,
      surprise, trust, anticipation
    * Moral
    * Agential: Whether you have power over outcomes that matter
      to you
    As a group decide if you want to play with any of these

    Optional Arenas
    * Sexual
    * Financial

    During character creation each PC will choose some personal arenas

    Example Personal Arenas
    * Duty
    * Authority
    * Acceptance
    * Intellectual

    When being raised ask, were the characters motivatons threatened,
    insulted, invoked, or denied to them?
    * If so they may roll that  motivation dice (but only once)

    Also ask this when taking fallout.
    * If so add the motivation dice to  the fallout dice (every time).

    Ask this when you *Give*, if so upgrade your permanent fallout die
    * starts at 1d4 goes through 2d4, 3d4, 1d6, 1d8, 1d10, 1d12, 2d6,
      3d6, 2d8, 3d8, 2d10, 2d12, 3d10, 3d12


    Escalation proceeds within an arena
